import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};

export const aimlComponents: CBREntry[] = [
  {
    id: 'generic_ml_model_server',
    display_name: 'ML Model Server',
    category: ComponentCategory.AIML,
    generic_equivalent: null,
    capacity: { max_rps: 500, latency_p50_ms: 100, latency_p99_ms: 1000 },
    saturation_curve: {
      coefficients: [1, 0.5, 4.0],
      description: 'GPU-bound; latency flat until batch queue fills, then steep',
    },
    cold_start: { base_latency_ms: 10000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_batch_size: 32, max_model_size_gb: 10, gpu_memory_gb: 24 },
    az_config: { min_az: 1, max_az: 2, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'GPU OOM',
        trigger_condition: 'batch_size * model_activations > GPU memory',
        impact: 'inference fails; CUDA OOM error',
        recovery_time_ms: 5000,
      },
      {
        name: 'Model Version Mismatch',
        trigger_condition: 'client sends request for deprecated model version',
        impact: '404 or incorrect inference results',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'GPU hour', base_cost_usd: 2.5, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'ml_model',
    properties: [
      {
        key: 'framework',
        label: 'Framework',
        type: 'select',
        default: 'torchserve',
        options: ['torchserve', 'triton', 'tensorflow_serving', 'onnx_runtime', 'ray_serve'],
        description: 'Model serving framework',
      },
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 1,
        min: 1,
        max: 100,
        description: 'Model server replicas',
      },
      {
        key: 'batch_size',
        label: 'Max Batch Size',
        type: 'number',
        default: 8,
        min: 1,
        max: 256,
        description: 'Dynamic batching max batch size',
      },
      {
        key: 'gpu',
        label: 'GPU Accelerated',
        type: 'boolean',
        default: true,
        description: 'Use GPU for inference',
      },
    ],
  },
  {
    id: 'generic_feature_store',
    display_name: 'Feature Store',
    category: ComponentCategory.AIML,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 5, latency_p99_ms: 30 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_features: 1000000, max_entities: 100000000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 3 },
    failure_modes: [
      {
        name: 'Feature Skew',
        trigger_condition: 'training features differ from serving features',
        impact: 'model predictions degrade; training-serving skew',
        recovery_time_ms: 0,
      },
      {
        name: 'Online Store Failure',
        trigger_condition: 'Redis/DynamoDB online store unreachable',
        impact: 'real-time feature lookups fail; model fallback to defaults',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'ml_model',
    properties: [
      {
        key: 'online_store',
        label: 'Online Store',
        type: 'select',
        default: 'redis',
        options: ['redis', 'dynamodb', 'bigtable', 'cassandra'],
        description: 'Low-latency online feature store',
      },
      {
        key: 'offline_store',
        label: 'Offline Store',
        type: 'select',
        default: 's3_parquet',
        options: ['s3_parquet', 'bigquery', 'snowflake', 'hive'],
        description: 'Batch offline feature store',
      },
      {
        key: 'feature_ttl_s',
        label: 'Feature TTL',
        type: 'number',
        default: 3600,
        min: 60,
        max: 86400,
        unit: 's',
        description: 'Online feature expiry',
      },
    ],
  },
  {
    id: 'generic_vector_database',
    display_name: 'Vector Database',
    category: ComponentCategory.AIML,
    generic_equivalent: null,
    capacity: { max_rps: 1000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: {
      coefficients: [1, 0.3, 3.0],
      description: 'ANN index search is CPU-intensive; degrades sharply under load',
    },
    cold_start: { base_latency_ms: 5000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_vectors: 1000000000, max_dimensions: 65536 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Index Build Latency',
        trigger_condition: 'large batch upsert triggers index rebuild',
        impact: 'queries slower during re-indexing window',
        recovery_time_ms: 300000,
      },
      {
        name: 'Memory Exhaustion',
        trigger_condition: 'vector index too large for RAM',
        impact: 'disk-based ANN search; 10-100x latency increase',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'GB vector data/month', base_cost_usd: 0.095, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'ml_model',
    properties: [
      {
        key: 'dimensions',
        label: 'Embedding Dimensions',
        type: 'number',
        default: 1536,
        min: 64,
        max: 65536,
        description: 'Vector embedding dimensions',
      },
      {
        key: 'index_type',
        label: 'Index Type',
        type: 'select',
        default: 'hnsw',
        options: ['hnsw', 'ivf_flat', 'ivf_pq', 'flat'],
        description: 'ANN index algorithm',
      },
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 1,
        min: 1,
        max: 10,
        description: 'Query node replicas',
      },
    ],
  },
  {
    id: 'generic_embedding_service',
    display_name: 'Embedding Service',
    category: ComponentCategory.AIML,
    generic_equivalent: 'generic_ml_model_server',
    capacity: { max_rps: 2000, latency_p50_ms: 50, latency_p99_ms: 300 },
    saturation_curve: {
      coefficients: [1, 0.3, 2.5],
      description: 'Batch embedding efficient; sequential requests saturate GPU',
    },
    cold_start: { base_latency_ms: 8000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_tokens_per_request: 8192, max_batch_size: 100 },
    az_config: { min_az: 1, max_az: 2, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Token Limit Exceeded',
        trigger_condition: 'input_tokens > max_tokens_per_request',
        impact: 'request rejected; caller must truncate',
        recovery_time_ms: 0,
      },
      {
        name: 'Model Warmup',
        trigger_condition: 'service restart loads model into GPU memory',
        impact: 'first requests have high latency',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: { unit: 'million tokens', base_cost_usd: 0.1, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'ml_model',
    properties: [
      {
        key: 'model',
        label: 'Embedding Model',
        type: 'select',
        default: 'text-embedding-3-small',
        options: ['text-embedding-3-small', 'text-embedding-3-large', 'ada-002', 'custom'],
        description: 'Embedding model to use',
      },
      {
        key: 'dimensions',
        label: 'Output Dimensions',
        type: 'number',
        default: 1536,
        min: 256,
        max: 3072,
        description: 'Embedding output dimensions',
      },
      {
        key: 'cache_embeddings',
        label: 'Cache Embeddings',
        type: 'boolean',
        default: true,
        description: 'Cache embeddings by content hash',
      },
    ],
  },
  {
    id: 'generic_training_cluster',
    display_name: 'Training Cluster',
    category: ComponentCategory.AIML,
    generic_equivalent: null,
    capacity: { max_rps: 1, latency_p50_ms: 3600000, latency_p99_ms: 86400000 },
    saturation_curve: {
      coefficients: [1, 2.0, 8.0],
      description: 'GPU communication overhead scales super-linearly with cluster size',
    },
    cold_start: { base_latency_ms: 300000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_gpus: 1024, max_training_time_h: 720 },
    az_config: { min_az: 1, max_az: 1, cross_az_latency_ms: 0 },
    failure_modes: [
      {
        name: 'GPU Node Failure',
        trigger_condition: 'single GPU node crashes mid-training',
        impact: 'training job fails; must restore from last checkpoint',
        recovery_time_ms: 0,
      },
      {
        name: 'NaN Loss Divergence',
        trigger_condition: 'gradient explosion or bad hyperparameters',
        impact: 'training run wasted; must restart with corrected config',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'GPU hour', base_cost_usd: 3.0, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'ml_model',
    properties: [
      {
        key: 'gpu_count',
        label: 'GPU Count',
        type: 'number',
        default: 8,
        min: 1,
        max: 1024,
        description: 'Number of GPUs in training cluster',
      },
      {
        key: 'gpu_type',
        label: 'GPU Type',
        type: 'select',
        default: 'A100',
        options: ['T4', 'V100', 'A100', 'H100', 'H200'],
        description: 'GPU accelerator type',
      },
      {
        key: 'checkpoint_interval_steps',
        label: 'Checkpoint Interval',
        type: 'number',
        default: 1000,
        min: 100,
        max: 100000,
        unit: 'steps',
        description: 'Save checkpoint every N training steps',
      },
    ],
  },
  {
    id: 'generic_inference_endpoint',
    display_name: 'Inference Endpoint',
    category: ComponentCategory.AIML,
    generic_equivalent: 'generic_ml_model_server',
    capacity: { max_rps: 100, latency_p50_ms: 500, latency_p99_ms: 5000 },
    saturation_curve: {
      coefficients: [1, 0.5, 5.0],
      description: 'LLM inference is token-generation bound; scales poorly under concurrency',
    },
    cold_start: { base_latency_ms: 30000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'reject_429',
    limits: { max_context_tokens: 128000, max_output_tokens: 8192 },
    az_config: { min_az: 1, max_az: 2, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Context Length Exceeded',
        trigger_condition: 'input_tokens > max_context_tokens',
        impact: 'request rejected with 400 error',
        recovery_time_ms: 0,
      },
      {
        name: 'Rate Limit',
        trigger_condition: 'tokens per minute > quota',
        impact: '429 TooManyRequests; callers must backoff',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: { unit: 'million tokens', base_cost_usd: 10, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'ml_model',
    properties: [
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        default: 'gpt-4o',
        options: ['gpt-4o', 'gpt-4o-mini', 'claude-3-5-sonnet', 'llama-3-70b', 'mistral-large'],
        description: 'LLM model',
      },
      {
        key: 'max_tokens',
        label: 'Max Output Tokens',
        type: 'number',
        default: 1024,
        min: 1,
        max: 128000,
        unit: 'tokens',
        description: 'Max tokens per response',
      },
      {
        key: 'streaming',
        label: 'Streaming',
        type: 'boolean',
        default: true,
        description: 'Enable token streaming responses',
      },
    ],
  },
];
