import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

export const clientComponents: CBREntry[] = [
  {
    id: 'generic_web_browser',
    display_name: 'Web Browser',
    category: ComponentCategory.ClientEdge,
    generic_equivalent: null,
    capacity: { max_rps: 100, latency_p50_ms: 100, latency_p99_ms: 2000 },
    saturation_curve: {
      coefficients: [1, 0.5, 3.0],
      description: 'Browser-side; connection limit and JS thread are bottlenecks',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_concurrent_http_connections: 6, max_websocket_connections: 255 },
    az_config: null,
    failure_modes: [
      {
        name: 'Connection Pool Limit',
        trigger_condition: 'concurrent requests > max_concurrent_http_connections per host',
        impact: 'additional requests queue; waterfall lengthens',
        recovery_time_ms: 0,
      },
      {
        name: 'JS Main Thread Block',
        trigger_condition: 'heavy computation on main thread',
        impact: 'UI unresponsive; interactions delayed',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'browser',
    properties: [
      {
        key: 'protocol',
        label: 'Protocol',
        type: 'select',
        default: 'https',
        options: ['https', 'http'],
        description: 'Communication protocol',
      },
      {
        key: 'http_version',
        label: 'HTTP Version',
        type: 'select',
        default: 'h2',
        options: ['h1.1', 'h2', 'h3'],
        description: 'HTTP protocol version',
      },
      {
        key: 'service_worker',
        label: 'Service Worker',
        type: 'boolean',
        default: false,
        description: 'Enable service worker for offline/caching',
      },
    ],
  },
  {
    id: 'generic_mobile_client',
    display_name: 'Mobile Client',
    category: ComponentCategory.ClientEdge,
    generic_equivalent: null,
    capacity: { max_rps: 20, latency_p50_ms: 200, latency_p99_ms: 5000 },
    saturation_curve: {
      coefficients: [1, 1.0, 5.0],
      description: 'Network variability and battery constraints dominate',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_background_fetch_mb: 200 },
    az_config: null,
    failure_modes: [
      {
        name: 'Network Transition',
        trigger_condition: 'WiFi to cellular or APN change',
        impact: 'connection reset; in-flight requests fail',
        recovery_time_ms: 3000,
      },
      {
        name: 'App Backgrounded',
        trigger_condition: 'OS suspends app',
        impact: 'network connections closed; reconnect on foreground',
        recovery_time_ms: 1000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'mobile',
    properties: [
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        default: 'ios',
        options: ['ios', 'android', 'react_native', 'flutter'],
        description: 'Mobile platform',
      },
      {
        key: 'offline_mode',
        label: 'Offline Support',
        type: 'boolean',
        default: false,
        description: 'Enable offline data sync',
      },
      {
        key: 'push_notifications',
        label: 'Push Notifications',
        type: 'boolean',
        default: true,
        description: 'Enable push notification support',
      },
    ],
  },
  {
    id: 'generic_iot_device',
    display_name: 'IoT Device',
    category: ComponentCategory.ClientEdge,
    generic_equivalent: null,
    capacity: { max_rps: 1, latency_p50_ms: 500, latency_p99_ms: 10000 },
    saturation_curve: {
      coefficients: [1, 2.0, 8.0],
      description: 'CPU/battery constrained; very limited concurrency',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_payload_kb: 128, max_message_frequency_s: 1 },
    az_config: null,
    failure_modes: [
      {
        name: 'Connectivity Loss',
        trigger_condition: 'WiFi/cellular signal lost',
        impact: 'messages queued locally; sent when reconnected',
        recovery_time_ms: 30000,
      },
      {
        name: 'Battery Depletion',
        trigger_condition: 'battery < threshold',
        impact: 'device goes offline; data loss if not persisted',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'iot',
    properties: [
      {
        key: 'protocol',
        label: 'Protocol',
        type: 'select',
        default: 'mqtt',
        options: ['mqtt', 'mqtt5', 'amqp', 'coap', 'https'],
        description: 'IoT communication protocol',
      },
      {
        key: 'telemetry_interval_s',
        label: 'Telemetry Interval',
        type: 'number',
        default: 60,
        min: 1,
        max: 3600,
        unit: 's',
        description: 'Data reporting frequency',
      },
      {
        key: 'device_count',
        label: 'Device Count',
        type: 'number',
        default: 1000,
        min: 1,
        max: 10000000,
        description: 'Number of devices in fleet',
      },
    ],
  },
  {
    id: 'generic_edge_node',
    display_name: 'Edge Node',
    category: ComponentCategory.ClientEdge,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 2, latency_p99_ms: 15 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'Local processing; constrained by hardware specs',
    },
    cold_start: { base_latency_ms: 5000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'shed',
    limits: { max_storage_gb: 1000, max_ram_gb: 64 },
    az_config: null,
    failure_modes: [
      {
        name: 'Cloud Connectivity Loss',
        trigger_condition: 'WAN link down',
        impact: 'edge operates in offline mode; sync resumes on reconnect',
        recovery_time_ms: 0,
      },
      {
        name: 'Storage Failure',
        trigger_condition: 'local disk failure',
        impact: 'edge data loss if no redundancy',
        recovery_time_ms: 3600000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'edge_node',
    properties: [
      {
        key: 'cpu_cores',
        label: 'CPU Cores',
        type: 'number',
        default: 4,
        min: 1,
        max: 64,
        description: 'Edge node CPU cores',
      },
      {
        key: 'local_inference',
        label: 'Local Inference',
        type: 'boolean',
        default: false,
        description: 'Run ML inference locally on edge',
      },
      {
        key: 'sync_interval_s',
        label: 'Cloud Sync Interval',
        type: 'number',
        default: 300,
        min: 10,
        max: 86400,
        unit: 's',
        description: 'Interval for cloud data synchronization',
      },
    ],
  },
  {
    id: 'generic_cli_client',
    display_name: 'CLI Client',
    category: ComponentCategory.ClientEdge,
    generic_equivalent: null,
    capacity: { max_rps: 10, latency_p50_ms: 500, latency_p99_ms: 5000 },
    saturation_curve: {
      coefficients: [1, 0.5, 2.0],
      description: 'Human-driven; not a latency-sensitive path',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_concurrent_requests: 4, max_output_size_mb: 100 },
    az_config: null,
    failure_modes: [
      {
        name: 'Timeout',
        trigger_condition: 'API response > cli_timeout setting',
        impact: 'command fails; user must retry',
        recovery_time_ms: 0,
      },
      {
        name: 'Credential Expiry',
        trigger_condition: 'auth token expires mid-session',
        impact: 'commands fail with 401; user must re-auth',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'cli',
    properties: [
      {
        key: 'timeout_s',
        label: 'Request Timeout',
        type: 'number',
        default: 30,
        min: 1,
        max: 600,
        unit: 's',
        description: 'CLI API call timeout',
      },
      {
        key: 'output_format',
        label: 'Output Format',
        type: 'select',
        default: 'json',
        options: ['json', 'yaml', 'table', 'text'],
        description: 'Default output format',
      },
      {
        key: 'retries',
        label: 'Retries',
        type: 'number',
        default: 3,
        min: 0,
        max: 10,
        description: 'Retry on transient failures',
      },
    ],
  },
  {
    id: 'generic_third_party_api',
    display_name: 'Third-Party API',
    category: ComponentCategory.ClientEdge,
    generic_equivalent: null,
    capacity: { max_rps: 1000, latency_p50_ms: 100, latency_p99_ms: 1000 },
    saturation_curve: {
      coefficients: [1, 0.3, 2.0],
      description: 'External dependency; unpredictable; rate limits apply',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { rate_limit_per_min: 60, max_burst: 100 },
    az_config: null,
    failure_modes: [
      {
        name: 'Rate Limit',
        trigger_condition: 'calls per minute > provider limit',
        impact: '429 errors; application must backoff',
        recovery_time_ms: 60000,
      },
      {
        name: 'Provider Outage',
        trigger_condition: 'third-party API unavailable',
        impact: 'all calls fail; timeout if no circuit breaker',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'cli',
    properties: [
      {
        key: 'timeout_ms',
        label: 'Timeout',
        type: 'number',
        default: 5000,
        min: 100,
        max: 60000,
        unit: 'ms',
        description: 'API call timeout',
      },
      {
        key: 'circuit_breaker',
        label: 'Circuit Breaker',
        type: 'boolean',
        default: true,
        description: 'Enable circuit breaker for external calls',
      },
      {
        key: 'retry_on_429',
        label: 'Retry on Rate Limit',
        type: 'boolean',
        default: true,
        description: 'Automatically retry with backoff on 429',
      },
    ],
  },
];
