import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};
const STEEP_CURVE = {
  coefficients: [1, 0.5, 4.0],
  description: 'Steep degradation above 70% load',
};

export const computeComponents: CBREntry[] = [
  {
    id: 'generic_web_server',
    display_name: 'Web Server',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 5, latency_p99_ms: 25 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_connections: 10000, max_request_size_mb: 100 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Connection Exhaustion',
        trigger_condition: 'active_connections >= max_connections',
        impact: 'new connections rejected',
        recovery_time_ms: 5000,
      },
      {
        name: 'OOM Crash',
        trigger_condition: 'memory_usage > 95%',
        impact: 'process restart',
        recovery_time_ms: 8000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'web_server',
    properties: [
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 2,
        min: 1,
        max: 100,
        description: 'Number of server instances',
      },
      {
        key: 'max_rps',
        label: 'Max RPS',
        type: 'number',
        default: 10000,
        min: 100,
        max: 500000,
        unit: 'req/s',
        description: 'Max requests per second per replica',
      },
      {
        key: 'tls_termination',
        label: 'TLS Termination',
        type: 'boolean',
        default: true,
        description: 'Terminate TLS at this server',
      },
      {
        key: 'keep_alive_timeout',
        label: 'Keep-Alive Timeout',
        type: 'number',
        default: 65,
        min: 0,
        max: 300,
        unit: 's',
        description: 'HTTP keep-alive connection timeout',
      },
    ],
  },
  {
    id: 'generic_app_server',
    display_name: 'App Server',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 20, latency_p99_ms: 100 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { thread_pool_size: 200, max_queue_depth: 1000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Thread Pool Exhaustion',
        trigger_condition:
          'active_threads >= thread_pool_size && queue_depth >= max_queue_depth',
        impact: 'requests rejected with 503',
        recovery_time_ms: 3000,
      },
      {
        name: 'GC Pause',
        trigger_condition: 'heap_usage > 85%',
        impact: 'latency spike 500ms–2s',
        recovery_time_ms: 2000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'app_server',
    properties: [
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 2,
        min: 1,
        max: 50,
        description: 'Number of app server instances',
      },
      {
        key: 'thread_pool_size',
        label: 'Thread Pool',
        type: 'number',
        default: 200,
        min: 10,
        max: 2000,
        description: 'Max concurrent threads',
      },
      {
        key: 'heap_size_gb',
        label: 'Heap Size',
        type: 'number',
        default: 4,
        min: 1,
        max: 64,
        unit: 'GB',
        description: 'JVM/runtime heap size',
      },
      {
        key: 'runtime',
        label: 'Runtime',
        type: 'select',
        default: 'jvm',
        options: ['jvm', 'node', 'python', 'ruby', 'go'],
        description: 'Application runtime',
      },
    ],
  },
  {
    id: 'generic_microservice',
    display_name: 'Microservice',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 3000, latency_p50_ms: 10, latency_p99_ms: 50 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_instances: 20, circuit_breaker_threshold: 0.5 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Cascading Failure',
        trigger_condition: 'upstream_error_rate > 50%',
        impact: 'circuit breaker opens, fail-fast',
        recovery_time_ms: 30000,
      },
      {
        name: 'Memory Leak',
        trigger_condition: 'memory_growth_rate > 0 sustained 10min',
        impact: 'OOM after time, pod restart',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'microservice',
    properties: [
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 3,
        min: 1,
        max: 50,
        description: 'Number of pod replicas',
      },
      {
        key: 'circuit_breaker',
        label: 'Circuit Breaker',
        type: 'boolean',
        default: true,
        description: 'Enable circuit breaker pattern',
      },
      {
        key: 'timeout_ms',
        label: 'Request Timeout',
        type: 'number',
        default: 5000,
        min: 100,
        max: 30000,
        unit: 'ms',
        description: 'Downstream request timeout',
      },
      {
        key: 'retry_count',
        label: 'Retry Count',
        type: 'number',
        default: 3,
        min: 0,
        max: 10,
        description: 'Number of retries on failure',
      },
    ],
  },
  {
    id: 'generic_serverless',
    display_name: 'Serverless Function',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 1000, latency_p50_ms: 15, latency_p99_ms: 200 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.5],
      description: 'Scales horizontally; cold starts dominate tail latency',
    },
    cold_start: {
      base_latency_ms: 200,
      runtime_overrides: { nodejs18: 80, python311: 120, java17: 500, go: 60, dotnet6: 350 },
      vpc_penalty_ms: 500,
    },
    throttle_behaviour: 'queue',
    limits: { max_concurrent_executions: 1000, max_memory_mb: 10240, max_timeout_s: 900 },
    az_config: null,
    failure_modes: [
      {
        name: 'Concurrency Throttle',
        trigger_condition: 'concurrent_executions >= max_concurrent_executions',
        impact: 'requests queued or rejected with 429',
        recovery_time_ms: 1000,
      },
      {
        name: 'Cold Start Spike',
        trigger_condition: 'idle_duration > 5min',
        impact: 'p99 latency spike by runtime cold_start penalty',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'invocations', base_cost_usd: 0.0000002, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'serverless_function',
    properties: [
      {
        key: 'runtime',
        label: 'Runtime',
        type: 'select',
        default: 'nodejs18',
        options: ['nodejs18', 'python311', 'java17', 'go', 'dotnet6'],
        description: 'Function runtime environment',
      },
      {
        key: 'memory_mb',
        label: 'Memory',
        type: 'number',
        default: 512,
        min: 128,
        max: 10240,
        unit: 'MB',
        description: 'Function memory allocation',
      },
      {
        key: 'timeout_s',
        label: 'Timeout',
        type: 'number',
        default: 30,
        min: 1,
        max: 900,
        unit: 's',
        description: 'Max execution duration',
      },
      {
        key: 'provisioned_concurrency',
        label: 'Provisioned Concurrency',
        type: 'number',
        default: 0,
        min: 0,
        max: 500,
        description: 'Pre-warmed instances to eliminate cold starts',
      },
    ],
  },
  {
    id: 'generic_vm',
    display_name: 'VM Instance',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 8000, latency_p50_ms: 8, latency_p99_ms: 40 },
    saturation_curve: QUAD_CURVE,
    cold_start: { base_latency_ms: 30000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'shed',
    limits: { max_vcpus: 96, max_ram_gb: 768, max_network_gbps: 25 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Host Failure',
        trigger_condition: 'hardware_fault',
        impact: 'instance terminated, replacement ~60s',
        recovery_time_ms: 60000,
      },
      {
        name: 'CPU Steal',
        trigger_condition: 'noisy_neighbor on shared host',
        impact: 'CPU performance degrades 10–40%',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'hour', base_cost_usd: 0.096, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'vm_instance',
    properties: [
      {
        key: 'instance_type',
        label: 'Instance Type',
        type: 'select',
        default: 't3.medium',
        options: ['t3.small', 't3.medium', 't3.large', 'm5.large', 'm5.xlarge', 'c5.large', 'c5.xlarge'],
        description: 'VM instance size class',
      },
      {
        key: 'count',
        label: 'Instance Count',
        type: 'number',
        default: 2,
        min: 1,
        max: 100,
        description: 'Number of VM instances',
      },
      {
        key: 'auto_scaling',
        label: 'Auto Scaling',
        type: 'boolean',
        default: false,
        description: 'Enable auto-scaling group',
      },
      {
        key: 'spot_instance',
        label: 'Spot/Preemptible',
        type: 'boolean',
        default: false,
        description: 'Use spot instances (cheaper, interruptible)',
      },
    ],
  },
  {
    id: 'generic_docker',
    display_name: 'Docker Container',
    category: ComponentCategory.Compute,
    generic_equivalent: 'generic_microservice',
    capacity: { max_rps: 5000, latency_p50_ms: 8, latency_p99_ms: 35 },
    saturation_curve: QUAD_CURVE,
    cold_start: { base_latency_ms: 2000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_cpu_cores: 4, max_memory_mb: 8192 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'OOM Kill',
        trigger_condition: 'memory_usage > container_limit',
        impact: 'container restart',
        recovery_time_ms: 3000,
      },
      {
        name: 'Image Pull Failure',
        trigger_condition: 'registry_unavailable at startup',
        impact: 'container fails to start',
        recovery_time_ms: 300000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'docker',
    properties: [
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 2,
        min: 1,
        max: 50,
        description: 'Container replicas',
      },
      {
        key: 'cpu_limit',
        label: 'CPU Limit',
        type: 'number',
        default: 1,
        min: 0.1,
        max: 16,
        unit: 'cores',
        description: 'CPU core limit per container',
      },
      {
        key: 'memory_mb',
        label: 'Memory Limit',
        type: 'number',
        default: 512,
        min: 64,
        max: 8192,
        unit: 'MB',
        description: 'Memory limit per container',
      },
      {
        key: 'restart_policy',
        label: 'Restart Policy',
        type: 'select',
        default: 'always',
        options: ['always', 'on-failure', 'unless-stopped', 'no'],
        description: 'Container restart policy',
      },
    ],
  },
  {
    id: 'generic_kubernetes',
    display_name: 'Kubernetes',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 5, latency_p99_ms: 20 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'Scales via HPA; latency stays flat until node saturation',
    },
    cold_start: { base_latency_ms: 5000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_pods_per_node: 110, max_nodes: 5000, api_qps_limit: 1000 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Node Pressure Eviction',
        trigger_condition: 'node_memory_pressure OR node_disk_pressure',
        impact: 'pods evicted, reschedule delay 30–60s',
        recovery_time_ms: 60000,
      },
      {
        name: 'API Server Overload',
        trigger_condition: 'api_requests > api_qps_limit',
        impact: 'control plane throttling, slower pod scheduling',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'kubernetes',
    properties: [
      {
        key: 'node_count',
        label: 'Node Count',
        type: 'number',
        default: 3,
        min: 1,
        max: 5000,
        description: 'Number of worker nodes',
      },
      {
        key: 'node_type',
        label: 'Node Type',
        type: 'select',
        default: 'm5.large',
        options: ['t3.medium', 'm5.large', 'm5.xlarge', 'c5.large', 'c5.2xlarge'],
        description: 'Worker node instance type',
      },
      {
        key: 'hpa_enabled',
        label: 'HPA Enabled',
        type: 'boolean',
        default: true,
        description: 'Horizontal Pod Autoscaler',
      },
      {
        key: 'max_pods',
        label: 'Max Pods/Node',
        type: 'number',
        default: 110,
        min: 10,
        max: 250,
        description: 'Maximum pods per node',
      },
    ],
  },
  {
    id: 'generic_nginx',
    display_name: 'Nginx',
    category: ComponentCategory.Compute,
    generic_equivalent: 'generic_web_server',
    capacity: { max_rps: 50000, latency_p50_ms: 1, latency_p99_ms: 5 },
    saturation_curve: {
      coefficients: [1, 0.05, 0.5],
      description: 'Very flat curve; Nginx handles high load efficiently',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { worker_connections: 65535, max_file_descriptors: 65535 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Worker Process Crash',
        trigger_condition: 'unhandled signal or OOM',
        impact: 'master restarts worker, brief connection drop',
        recovery_time_ms: 500,
      },
      {
        name: 'File Descriptor Exhaustion',
        trigger_condition: 'open_fds >= max_file_descriptors',
        impact: 'new connections fail with EMFILE',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'nginx',
    properties: [
      {
        key: 'worker_processes',
        label: 'Worker Processes',
        type: 'number',
        default: 4,
        min: 1,
        max: 64,
        description: 'Number of Nginx worker processes (typically = CPU cores)',
      },
      {
        key: 'worker_connections',
        label: 'Worker Connections',
        type: 'number',
        default: 1024,
        min: 128,
        max: 65535,
        description: 'Max connections per worker',
      },
      {
        key: 'keepalive',
        label: 'Keepalive Requests',
        type: 'number',
        default: 100,
        min: 0,
        max: 10000,
        description: 'Max keepalive requests per connection',
      },
      {
        key: 'gzip',
        label: 'Gzip Compression',
        type: 'boolean',
        default: true,
        description: 'Enable response compression',
      },
    ],
  },
  {
    id: 'generic_microservice_grpc',
    display_name: 'gRPC Server',
    category: ComponentCategory.Compute,
    generic_equivalent: 'generic_microservice',
    capacity: { max_rps: 20000, latency_p50_ms: 3, latency_p99_ms: 15 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_concurrent_streams: 100, max_message_size_mb: 4 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Stream Exhaustion',
        trigger_condition: 'concurrent_streams >= max_concurrent_streams',
        impact: 'new calls fail with RESOURCE_EXHAUSTED',
        recovery_time_ms: 1000,
      },
      {
        name: 'Deadline Exceeded',
        trigger_condition: 'processing_time > client_deadline',
        impact: 'call cancelled, client retries',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'grpc',
    properties: [
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 3,
        min: 1,
        max: 50,
        description: 'Server replicas',
      },
      {
        key: 'max_concurrent_streams',
        label: 'Concurrent Streams',
        type: 'number',
        default: 100,
        min: 1,
        max: 1000,
        description: 'Max concurrent HTTP/2 streams per connection',
      },
      {
        key: 'tls',
        label: 'mTLS',
        type: 'boolean',
        default: true,
        description: 'Enable mutual TLS',
      },
      {
        key: 'reflection',
        label: 'Server Reflection',
        type: 'boolean',
        default: false,
        description: 'Enable gRPC server reflection API',
      },
    ],
  },
  {
    id: 'generic_graphql_server',
    display_name: 'GraphQL Server',
    category: ComponentCategory.Compute,
    generic_equivalent: 'generic_app_server',
    capacity: { max_rps: 2000, latency_p50_ms: 30, latency_p99_ms: 150 },
    saturation_curve: STEEP_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_query_depth: 10, max_query_complexity: 100, max_aliases: 30 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'N+1 Query Spiral',
        trigger_condition: 'unbatched resolver fan-out',
        impact: 'DB connection pool exhausted, cascading slowdown',
        recovery_time_ms: 15000,
      },
      {
        name: 'Query Complexity DoS',
        trigger_condition: 'malicious_query_complexity > threshold',
        impact: 'CPU spike, other requests starved',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'graphql',
    properties: [
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 2,
        min: 1,
        max: 30,
        description: 'Server replicas',
      },
      {
        key: 'max_depth',
        label: 'Max Query Depth',
        type: 'number',
        default: 10,
        min: 1,
        max: 20,
        description: 'Maximum query nesting depth',
      },
      {
        key: 'persisted_queries',
        label: 'Persisted Queries',
        type: 'boolean',
        default: false,
        description: 'Only allow pre-registered queries',
      },
      {
        key: 'dataloader',
        label: 'DataLoader Batching',
        type: 'boolean',
        default: true,
        description: 'Enable DataLoader N+1 prevention',
      },
    ],
  },
  {
    id: 'generic_websocket_server',
    display_name: 'WebSocket Server',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 500, latency_p50_ms: 5, latency_p99_ms: 20 },
    saturation_curve: {
      coefficients: [1, 0.3, 3.0],
      description: 'Connection memory limits scale horizontally',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_concurrent_connections: 50000, max_message_size_kb: 64 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Connection Flood',
        trigger_condition: 'active_connections >= max_concurrent_connections',
        impact: 'new connections rejected',
        recovery_time_ms: 0,
      },
      {
        name: 'Memory Pressure',
        trigger_condition: 'memory_per_connection * active_connections > heap',
        impact: 'OOM crash, all connections dropped',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'web_server',
    properties: [
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 2,
        min: 1,
        max: 50,
        description: 'Server replicas (behind sticky LB)',
      },
      {
        key: 'max_connections',
        label: 'Max Connections',
        type: 'number',
        default: 50000,
        min: 1000,
        max: 1000000,
        description: 'Max concurrent WebSocket connections per instance',
      },
      {
        key: 'ping_interval_s',
        label: 'Ping Interval',
        type: 'number',
        default: 30,
        min: 5,
        max: 120,
        unit: 's',
        description: 'WebSocket heartbeat interval',
      },
      {
        key: 'sticky_sessions',
        label: 'Sticky Sessions',
        type: 'boolean',
        default: true,
        description: 'Require sticky load balancing for WebSocket',
      },
    ],
  },
  {
    id: 'generic_edge_function',
    display_name: 'Edge Function',
    category: ComponentCategory.Compute,
    generic_equivalent: 'generic_serverless',
    capacity: { max_rps: 50000, latency_p50_ms: 2, latency_p99_ms: 10 },
    saturation_curve: {
      coefficients: [1, 0.05, 0.3],
      description: 'Runs at CDN edge; near-zero cold starts',
    },
    cold_start: { base_latency_ms: 5, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'shed',
    limits: { max_script_size_kb: 1024, max_execution_time_ms: 50, max_memory_mb: 128 },
    az_config: null,
    failure_modes: [
      {
        name: 'CPU Time Exceeded',
        trigger_condition: 'execution_time > max_execution_time_ms',
        impact: 'function terminated, fallback to origin',
        recovery_time_ms: 0,
      },
      {
        name: 'Script Deploy Error',
        trigger_condition: 'invalid syntax or size exceeded at deploy',
        impact: 'deployment blocked',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'requests', base_cost_usd: 0.0000005, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'serverless_function',
    properties: [
      {
        key: 'runtime',
        label: 'Runtime',
        type: 'select',
        default: 'v8isolate',
        options: ['v8isolate', 'wasm'],
        description: 'Edge runtime type',
      },
      {
        key: 'regions',
        label: 'Deployed Regions',
        type: 'number',
        default: 30,
        min: 1,
        max: 200,
        description: 'Number of edge PoPs',
      },
      {
        key: 'cache_ttl',
        label: 'Response Cache TTL',
        type: 'number',
        default: 0,
        min: 0,
        max: 86400,
        unit: 's',
        description: 'Cache edge function responses',
      },
      {
        key: 'fallback_origin',
        label: 'Fallback on Error',
        type: 'boolean',
        default: true,
        description: 'Fall back to origin on function failure',
      },
    ],
  },
  {
    id: 'generic_worker_node',
    display_name: 'Worker Node',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 100, latency_p50_ms: 1000, latency_p99_ms: 5000 },
    saturation_curve: {
      coefficients: [1, 0.5, 2.0],
      description: 'Queue-based; throughput limited by job size',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_concurrent_jobs: 10, max_job_memory_mb: 4096 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Job Timeout',
        trigger_condition: 'job_duration > max_job_timeout',
        impact: 'job marked failed, retried',
        recovery_time_ms: 0,
      },
      {
        name: 'Worker Crash Mid-Job',
        trigger_condition: 'OOM or panic',
        impact: 'job lost if not idempotent',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'app_server',
    properties: [
      {
        key: 'workers',
        label: 'Worker Count',
        type: 'number',
        default: 5,
        min: 1,
        max: 1000,
        description: 'Number of worker processes',
      },
      {
        key: 'concurrency',
        label: 'Jobs Per Worker',
        type: 'number',
        default: 2,
        min: 1,
        max: 20,
        description: 'Concurrent jobs per worker',
      },
      {
        key: 'job_timeout_s',
        label: 'Job Timeout',
        type: 'number',
        default: 300,
        min: 1,
        max: 86400,
        unit: 's',
        description: 'Max time before job is killed',
      },
      {
        key: 'retry_on_failure',
        label: 'Auto-Retry',
        type: 'boolean',
        default: true,
        description: 'Retry failed jobs automatically',
      },
    ],
  },
  {
    id: 'generic_batch_processor',
    display_name: 'Batch Processor',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 10, latency_p50_ms: 60000, latency_p99_ms: 300000 },
    saturation_curve: {
      coefficients: [1, 1.0, 3.0],
      description: 'Throughput-bound; latency scales with batch size',
    },
    cold_start: { base_latency_ms: 10000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_batch_size: 100000, max_memory_gb: 32 },
    az_config: { min_az: 1, max_az: 1, cross_az_latency_ms: 0 },
    failure_modes: [
      {
        name: 'Batch Failure',
        trigger_condition: 'unhandled exception during processing',
        impact: 'batch retried or sent to DLQ',
        recovery_time_ms: 0,
      },
      {
        name: 'Checkpoint Miss',
        trigger_condition: 'failure before checkpoint write',
        impact: 'reprocessing from last checkpoint',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'app_server',
    properties: [
      {
        key: 'batch_size',
        label: 'Batch Size',
        type: 'number',
        default: 1000,
        min: 1,
        max: 1000000,
        description: 'Records per batch',
      },
      {
        key: 'parallelism',
        label: 'Parallelism',
        type: 'number',
        default: 4,
        min: 1,
        max: 128,
        description: 'Parallel processing threads',
      },
      {
        key: 'schedule',
        label: 'Schedule',
        type: 'select',
        default: 'on_demand',
        options: ['on_demand', 'hourly', 'daily', 'weekly'],
        description: 'Batch execution trigger',
      },
      {
        key: 'checkpoint_interval',
        label: 'Checkpoint Interval',
        type: 'number',
        default: 10000,
        min: 100,
        max: 1000000,
        unit: 'records',
        description: 'Checkpoint every N records',
      },
    ],
  },
  {
    id: 'generic_job_scheduler',
    display_name: 'Job Scheduler',
    category: ComponentCategory.Compute,
    generic_equivalent: null,
    capacity: { max_rps: 500, latency_p50_ms: 50, latency_p99_ms: 200 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_scheduled_jobs: 100000, max_concurrent_jobs: 1000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Clock Skew',
        trigger_condition: 'NTP drift > 1s',
        impact: 'jobs triggered at wrong time',
        recovery_time_ms: 0,
      },
      {
        name: 'Scheduler Crash',
        trigger_condition: 'OOM or panic',
        impact: 'all pending jobs paused until restart',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'app_server',
    properties: [
      {
        key: 'max_concurrent',
        label: 'Max Concurrent Jobs',
        type: 'number',
        default: 100,
        min: 1,
        max: 10000,
        description: 'Concurrent job execution limit',
      },
      {
        key: 'retry_attempts',
        label: 'Retry Attempts',
        type: 'number',
        default: 3,
        min: 0,
        max: 10,
        description: 'Job retry attempts on failure',
      },
      {
        key: 'distributed',
        label: 'Distributed Mode',
        type: 'boolean',
        default: true,
        description: 'Run scheduler in distributed HA mode',
      },
      {
        key: 'timezone',
        label: 'Timezone',
        type: 'select',
        default: 'UTC',
        options: ['UTC', 'America/New_York', 'Europe/London', 'Asia/Tokyo'],
        description: 'Scheduler timezone for cron jobs',
      },
    ],
  },
  {
    id: 'generic_bare_metal',
    display_name: 'Bare Metal Server',
    category: ComponentCategory.Compute,
    generic_equivalent: 'generic_vm',
    capacity: { max_rps: 100000, latency_p50_ms: 1, latency_p99_ms: 5 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.5],
      description: 'No virtualization overhead; very flat curve',
    },
    cold_start: { base_latency_ms: 180000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'shed',
    limits: { max_vcpus: 224, max_ram_gb: 3072, max_network_gbps: 100 },
    az_config: { min_az: 1, max_az: 1, cross_az_latency_ms: 0 },
    failure_modes: [
      {
        name: 'Hardware Failure',
        trigger_condition: 'disk/NIC/CPU hardware fault',
        impact: 'server down until replacement (4–24h)',
        recovery_time_ms: 14400000,
      },
      {
        name: 'Firmware Update',
        trigger_condition: 'scheduled maintenance',
        impact: 'planned downtime 30–60min',
        recovery_time_ms: 3600000,
      },
    ],
    cost_model: { unit: 'hour', base_cost_usd: 2.5, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'vm_instance',
    properties: [
      {
        key: 'count',
        label: 'Server Count',
        type: 'number',
        default: 1,
        min: 1,
        max: 100,
        description: 'Number of bare metal servers',
      },
      {
        key: 'cpu_cores',
        label: 'CPU Cores',
        type: 'number',
        default: 64,
        min: 8,
        max: 224,
        description: 'Physical CPU cores per server',
      },
      {
        key: 'ram_gb',
        label: 'RAM',
        type: 'number',
        default: 256,
        min: 32,
        max: 3072,
        unit: 'GB',
        description: 'RAM per server',
      },
      {
        key: 'raid_level',
        label: 'RAID Level',
        type: 'select',
        default: 'RAID-10',
        options: ['RAID-0', 'RAID-1', 'RAID-5', 'RAID-10', 'JBOD'],
        description: 'Local disk RAID configuration',
      },
    ],
  },
];
