import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};
const STEEP_CURVE = {
  coefficients: [1, 0.3, 4.0],
  description: 'Connection pool exhaustion causes steep degradation',
};

export const databaseComponents: CBREntry[] = [
  {
    id: 'generic_postgresql',
    display_name: 'PostgreSQL',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: STEEP_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_connections: 100, max_connections_xlarge: 500, max_storage_tb: 64 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Connection Pool Exhaustion',
        trigger_condition: 'active_connections >= max_connections',
        impact: 'new queries fail immediately',
        recovery_time_ms: 0,
      },
      {
        name: 'Replication Lag',
        trigger_condition: 'write_volume > replica_throughput',
        impact: 'replica reads return stale data',
        recovery_time_ms: 30000,
      },
      {
        name: 'Bloat / Vacuum Needed',
        trigger_condition: 'dead_tuples > autovacuum_threshold',
        impact: '10–40% query slowdown until vacuum completes',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'postgresql',
    properties: [
      {
        key: 'instance_class',
        label: 'Instance Class',
        type: 'select',
        default: 'db.t3.medium',
        options: ['db.t3.small', 'db.t3.medium', 'db.m5.large', 'db.m5.xlarge', 'db.r5.large', 'db.r5.2xlarge'],
        description: 'Database instance size',
      },
      {
        key: 'max_connections',
        label: 'Max Connections',
        type: 'number',
        default: 100,
        min: 5,
        max: 5000,
        description: 'Maximum database connections',
      },
      {
        key: 'storage_gb',
        label: 'Storage',
        type: 'number',
        default: 100,
        min: 20,
        max: 65536,
        unit: 'GB',
        description: 'Allocated storage',
      },
      {
        key: 'read_replicas',
        label: 'Read Replicas',
        type: 'number',
        default: 1,
        min: 0,
        max: 5,
        description: 'Number of read replicas',
      },
      {
        key: 'multi_az',
        label: 'Multi-AZ',
        type: 'boolean',
        default: true,
        description: 'Synchronous standby replica',
      },
    ],
  },
  {
    id: 'generic_mysql',
    display_name: 'MySQL',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: STEEP_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_connections: 151, max_storage_tb: 64 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Connection Limit',
        trigger_condition: 'active_connections >= max_connections',
        impact: 'Too many connections error',
        recovery_time_ms: 0,
      },
      {
        name: 'Lock Contention',
        trigger_condition: 'concurrent_writes on same row',
        impact: 'transactions queue, latency spike',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'mysql',
    properties: [
      {
        key: 'instance_class',
        label: 'Instance Class',
        type: 'select',
        default: 'db.t3.medium',
        options: ['db.t3.small', 'db.t3.medium', 'db.m5.large', 'db.m5.xlarge', 'db.r5.large'],
        description: 'Database instance size',
      },
      {
        key: 'max_connections',
        label: 'Max Connections',
        type: 'number',
        default: 151,
        min: 10,
        max: 5000,
        description: 'Maximum database connections',
      },
      {
        key: 'storage_gb',
        label: 'Storage',
        type: 'number',
        default: 100,
        min: 20,
        max: 65536,
        unit: 'GB',
        description: 'Allocated storage',
      },
      {
        key: 'read_replicas',
        label: 'Read Replicas',
        type: 'number',
        default: 1,
        min: 0,
        max: 5,
        description: 'Number of read replicas',
      },
    ],
  },
  {
    id: 'generic_mongodb',
    display_name: 'MongoDB',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 3, latency_p99_ms: 30 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_connections: 200, max_document_size_mb: 16 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Primary Election',
        trigger_condition: 'primary node failure',
        impact: 'write unavailability ~10–30s during election',
        recovery_time_ms: 30000,
      },
      {
        name: 'Index Bloat',
        trigger_condition: 'high write volume without compact',
        impact: 'wiredTiger cache thrash, latency increase',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'mongodb',
    properties: [
      {
        key: 'replica_set_size',
        label: 'Replica Set Size',
        type: 'number',
        default: 3,
        min: 1,
        max: 7,
        description: 'Replica set member count',
      },
      {
        key: 'storage_gb',
        label: 'Storage',
        type: 'number',
        default: 100,
        min: 10,
        max: 4096,
        unit: 'GB',
        description: 'Allocated storage',
      },
      {
        key: 'sharding',
        label: 'Sharding',
        type: 'boolean',
        default: false,
        description: 'Enable horizontal sharding',
      },
      {
        key: 'read_concern',
        label: 'Read Concern',
        type: 'select',
        default: 'local',
        options: ['local', 'majority', 'linearizable'],
        description: 'Read consistency level',
      },
    ],
  },
  {
    id: 'generic_redis',
    display_name: 'Redis',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 100000, latency_p50_ms: 0.5, latency_p99_ms: 5 },
    saturation_curve: {
      coefficients: [1, 0.1, 1.0],
      description: 'In-memory; latency flat until memory eviction pressure',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_connections: 65000, max_memory_mb: 407552 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Memory Eviction',
        trigger_condition: 'used_memory >= maxmemory',
        impact: 'keys evicted per policy; cache miss spike',
        recovery_time_ms: 0,
      },
      {
        name: 'Failover',
        trigger_condition: 'primary node failure',
        impact: '1–3s write gap during sentinel/cluster failover',
        recovery_time_ms: 3000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'redis',
    properties: [
      {
        key: 'memory_mb',
        label: 'Memory',
        type: 'number',
        default: 1024,
        min: 64,
        max: 407552,
        unit: 'MB',
        description: 'Max memory allocation',
      },
      {
        key: 'eviction_policy',
        label: 'Eviction Policy',
        type: 'select',
        default: 'allkeys-lru',
        options: ['noeviction', 'allkeys-lru', 'volatile-lru', 'allkeys-random'],
        description: 'Key eviction policy when memory full',
      },
      {
        key: 'replication',
        label: 'Replication',
        type: 'boolean',
        default: true,
        description: 'Enable primary/replica replication',
      },
      {
        key: 'persistence',
        label: 'Persistence',
        type: 'select',
        default: 'rdb',
        options: ['none', 'rdb', 'aof', 'rdb+aof'],
        description: 'Data persistence mode',
      },
    ],
  },
  {
    id: 'generic_elasticsearch',
    display_name: 'Elasticsearch',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 3000, latency_p50_ms: 20, latency_p99_ms: 200 },
    saturation_curve: {
      coefficients: [1, 0.4, 3.5],
      description: 'JVM GC and shard routing overhead under load',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_shards_per_node: 1000, max_doc_size_mb: 100 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Shard Relocation Storm',
        trigger_condition: 'node failure triggers shard rebalance',
        impact: 'cluster red/yellow, I/O saturated during recovery',
        recovery_time_ms: 300000,
      },
      {
        name: 'JVM OOM',
        trigger_condition: 'heap usage > 85%',
        impact: 'node evicted, shard reallocation',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'elasticsearch',
    properties: [
      {
        key: 'node_count',
        label: 'Node Count',
        type: 'number',
        default: 3,
        min: 1,
        max: 100,
        description: 'Number of data nodes',
      },
      {
        key: 'shard_count',
        label: 'Shard Count',
        type: 'number',
        default: 5,
        min: 1,
        max: 1000,
        description: 'Primary shards per index',
      },
      {
        key: 'replicas',
        label: 'Replica Shards',
        type: 'number',
        default: 1,
        min: 0,
        max: 3,
        description: 'Replica shards per primary',
      },
      {
        key: 'heap_gb',
        label: 'JVM Heap',
        type: 'number',
        default: 8,
        min: 1,
        max: 32,
        unit: 'GB',
        description: 'JVM heap per node (max 32GB)',
      },
    ],
  },
  {
    id: 'generic_cassandra',
    display_name: 'Cassandra',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 3, latency_p99_ms: 20 },
    saturation_curve: {
      coefficients: [1, 0.15, 1.2],
      description: 'Linear scale-out; latency stable with proper partitioning',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_partition_size_mb: 100, max_column_count: 2000000000 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Hot Partition',
        trigger_condition: 'skewed partition key distribution',
        impact: 'single node overloaded; others idle',
        recovery_time_ms: 0,
      },
      {
        name: 'Compaction Storm',
        trigger_condition: 'write amplification > threshold',
        impact: 'disk I/O saturated, read latency spikes',
        recovery_time_ms: 120000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'cassandra',
    properties: [
      {
        key: 'node_count',
        label: 'Node Count',
        type: 'number',
        default: 3,
        min: 3,
        max: 100,
        description: 'Cassandra ring node count',
      },
      {
        key: 'replication_factor',
        label: 'Replication Factor',
        type: 'number',
        default: 3,
        min: 1,
        max: 5,
        description: 'Data replication factor',
      },
      {
        key: 'consistency_level',
        label: 'Consistency Level',
        type: 'select',
        default: 'LOCAL_QUORUM',
        options: ['ONE', 'QUORUM', 'LOCAL_QUORUM', 'ALL'],
        description: 'Read/write consistency level',
      },
      {
        key: 'compaction_strategy',
        label: 'Compaction Strategy',
        type: 'select',
        default: 'STCS',
        options: ['STCS', 'LCS', 'TWCS'],
        description: 'SSTable compaction strategy',
      },
    ],
  },
  {
    id: 'generic_wide_column_db',
    display_name: 'Wide-Column DB',
    category: ComponentCategory.Database,
    generic_equivalent: 'generic_cassandra',
    capacity: { max_rps: 30000, latency_p50_ms: 5, latency_p99_ms: 25 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_row_size_mb: 256, max_cells_per_row: 1000000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Hot Row',
        trigger_condition: 'single row accessed > 10000 rps',
        impact: 'single node hotspot, throttling',
        recovery_time_ms: 0,
      },
      {
        name: 'Tablet Split Storm',
        trigger_condition: 'rapid data growth triggers many splits',
        impact: 'temporary latency increase during split',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'app_server',
    properties: [
      {
        key: 'nodes',
        label: 'Nodes',
        type: 'number',
        default: 3,
        min: 1,
        max: 200,
        description: 'Cluster node count',
      },
      {
        key: 'replication_factor',
        label: 'Replication Factor',
        type: 'number',
        default: 3,
        min: 1,
        max: 5,
        description: 'Data replication factor',
      },
      {
        key: 'auto_scaling',
        label: 'Auto Scaling',
        type: 'boolean',
        default: true,
        description: 'Enable auto-scaling',
      },
    ],
  },
  {
    id: 'generic_graph_database',
    display_name: 'Graph Database',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 1000, latency_p50_ms: 20, latency_p99_ms: 200 },
    saturation_curve: {
      coefficients: [1, 0.5, 5.0],
      description: 'Deep graph traversals are exponentially expensive',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_nodes: 1000000000, max_relationships: 10000000000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 10 },
    failure_modes: [
      {
        name: 'Deep Traversal Timeout',
        trigger_condition: 'query depth > N hops unbounded',
        impact: 'query timeout, OOM risk',
        recovery_time_ms: 5000,
      },
      {
        name: 'Cache Eviction',
        trigger_condition: 'hot subgraph evicted from page cache',
        impact: 'disk I/O spike, latency 10x',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'neo4j',
    properties: [
      {
        key: 'heap_gb',
        label: 'Heap Size',
        type: 'number',
        default: 8,
        min: 2,
        max: 128,
        unit: 'GB',
        description: 'JVM heap size',
      },
      {
        key: 'page_cache_gb',
        label: 'Page Cache',
        type: 'number',
        default: 16,
        min: 1,
        max: 512,
        unit: 'GB',
        description: 'Page cache for graph data',
      },
      {
        key: 'cluster_mode',
        label: 'Cluster Mode',
        type: 'boolean',
        default: true,
        description: 'Enable causal clustering',
      },
    ],
  },
  {
    id: 'generic_timeseries_db',
    display_name: 'Time-Series DB',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 20000, latency_p50_ms: 2, latency_p99_ms: 20 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_series_cardinality: 10000000, max_retention_days: 730 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 3 },
    failure_modes: [
      {
        name: 'High Cardinality Explosion',
        trigger_condition: 'unique series > max_series_cardinality',
        impact: 'OOM, ingestion halts',
        recovery_time_ms: 0,
      },
      {
        name: 'Compaction Backlog',
        trigger_condition: 'ingest rate > compaction rate',
        impact: 'disk usage grows; query performance degrades',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'influxdb',
    properties: [
      {
        key: 'retention_days',
        label: 'Retention',
        type: 'number',
        default: 30,
        min: 1,
        max: 730,
        unit: 'days',
        description: 'Data retention period',
      },
      {
        key: 'downsample',
        label: 'Downsampling',
        type: 'boolean',
        default: true,
        description: 'Enable automatic data downsampling',
      },
      {
        key: 'ingest_rps',
        label: 'Ingest Rate',
        type: 'number',
        default: 10000,
        min: 100,
        max: 1000000,
        unit: 'points/s',
        description: 'Expected ingest rate',
      },
    ],
  },
  {
    id: 'generic_olap_database',
    display_name: 'OLAP Database',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 100, latency_p50_ms: 500, latency_p99_ms: 10000 },
    saturation_curve: {
      coefficients: [1, 1.0, 5.0],
      description: 'Query-heavy; concurrent analytical queries saturate quickly',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_concurrent_queries: 100, max_query_memory_gb: 128 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Memory Spill',
        trigger_condition: 'query exceeds per-query memory limit',
        impact: 'query fails or spills to disk, 10x slower',
        recovery_time_ms: 0,
      },
      {
        name: 'Concurrent Query Storm',
        trigger_condition: 'concurrent_queries > max_concurrent_queries',
        impact: 'queries queued, dashboard timeouts',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'clickhouse',
    properties: [
      {
        key: 'cluster_nodes',
        label: 'Cluster Nodes',
        type: 'number',
        default: 3,
        min: 1,
        max: 100,
        description: 'Number of ClickHouse/OLAP nodes',
      },
      {
        key: 'shards',
        label: 'Shards',
        type: 'number',
        default: 3,
        min: 1,
        max: 100,
        description: 'Number of data shards',
      },
      {
        key: 'compression',
        label: 'Compression',
        type: 'select',
        default: 'lz4',
        options: ['lz4', 'zstd', 'none'],
        description: 'Column data compression',
      },
    ],
  },
  {
    id: 'generic_sqlite',
    display_name: 'SQLite',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 500, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: {
      coefficients: [1, 0.5, 8.0],
      description: 'Write lock serialization causes rapid degradation under concurrent writes',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_db_size_gb: 281000, max_concurrent_writers: 1 },
    az_config: null,
    failure_modes: [
      {
        name: 'Write Lock Contention',
        trigger_condition: 'concurrent writes > 1',
        impact: 'writes serialized; high latency under concurrent load',
        recovery_time_ms: 0,
      },
      {
        name: 'File Corruption',
        trigger_condition: 'OS crash during write without WAL',
        impact: 'database corruption requires restore',
        recovery_time_ms: 3600000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'sqlite',
    properties: [
      {
        key: 'wal_mode',
        label: 'WAL Mode',
        type: 'boolean',
        default: true,
        description: 'Enable Write-Ahead Logging for concurrent reads',
      },
      {
        key: 'page_size_kb',
        label: 'Page Size',
        type: 'select',
        default: '4',
        options: ['1', '2', '4', '8', '16', '32', '64'],
        unit: 'KB',
        description: 'Database page size',
      },
      {
        key: 'cache_size_mb',
        label: 'Cache Size',
        type: 'number',
        default: 64,
        min: 1,
        max: 8192,
        unit: 'MB',
        description: 'In-memory page cache',
      },
    ],
  },
  {
    id: 'generic_mariadb',
    display_name: 'MariaDB',
    category: ComponentCategory.Database,
    generic_equivalent: 'generic_mysql',
    capacity: { max_rps: 5000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: STEEP_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_connections: 151, max_storage_tb: 64 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Connection Limit',
        trigger_condition: 'active_connections >= max_connections',
        impact: 'Too many connections error',
        recovery_time_ms: 0,
      },
      {
        name: 'Galera Replication Conflict',
        trigger_condition: 'write conflict in Galera cluster',
        impact: 'transaction rollback and retry',
        recovery_time_ms: 1000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'mariadb',
    properties: [
      {
        key: 'max_connections',
        label: 'Max Connections',
        type: 'number',
        default: 151,
        min: 10,
        max: 5000,
        description: 'Maximum database connections',
      },
      {
        key: 'galera_cluster',
        label: 'Galera Cluster',
        type: 'boolean',
        default: false,
        description: 'Enable Galera multi-master cluster',
      },
      {
        key: 'storage_gb',
        label: 'Storage',
        type: 'number',
        default: 100,
        min: 20,
        max: 65536,
        unit: 'GB',
        description: 'Allocated storage',
      },
    ],
  },
  {
    id: 'generic_enterprise_rdb',
    display_name: 'Relational DB (Enterprise)',
    category: ComponentCategory.Database,
    generic_equivalent: 'generic_postgresql',
    capacity: { max_rps: 20000, latency_p50_ms: 3, latency_p99_ms: 20 },
    saturation_curve: STEEP_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_sessions: 40000, max_storage_pb: 10 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 3 },
    failure_modes: [
      {
        name: 'License Violation',
        trigger_condition: 'CPU count exceeds license',
        impact: 'database shutdown or throttling',
        recovery_time_ms: 0,
      },
      {
        name: 'Undo Tablespace Exhaustion',
        trigger_condition: 'long running transactions > undo space',
        impact: 'ORA-01555: snapshot too old error',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: { unit: 'CPU core/year', base_cost_usd: 25000, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'oracle',
    properties: [
      {
        key: 'cpu_count',
        label: 'CPU Count',
        type: 'number',
        default: 4,
        min: 1,
        max: 512,
        description: 'Licensed CPU count',
      },
      {
        key: 'sga_gb',
        label: 'SGA Size',
        type: 'number',
        default: 16,
        min: 1,
        max: 4096,
        unit: 'GB',
        description: 'System Global Area memory',
      },
      {
        key: 'rac',
        label: 'RAC Cluster',
        type: 'boolean',
        default: false,
        description: 'Enable Real Application Clusters',
      },
    ],
  },
  {
    id: 'generic_distributed_sql',
    display_name: 'Distributed SQL',
    category: ComponentCategory.Database,
    generic_equivalent: 'generic_postgresql',
    capacity: { max_rps: 10000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_nodes: 150, max_db_size_pb: 10 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Cross-Region Latency',
        trigger_condition: 'geo-distributed writes require global consensus',
        impact: '2–5x write latency due to consensus round trips',
        recovery_time_ms: 0,
      },
      {
        name: 'Range Rebalancing',
        trigger_condition: 'data growth triggers range splits',
        impact: 'temporary hotspot during range migration',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'cockroachdb',
    properties: [
      {
        key: 'node_count',
        label: 'Node Count',
        type: 'number',
        default: 3,
        min: 3,
        max: 150,
        description: 'Number of nodes',
      },
      {
        key: 'regions',
        label: 'Regions',
        type: 'number',
        default: 1,
        min: 1,
        max: 10,
        description: 'Number of geographic regions',
      },
      {
        key: 'replication_factor',
        label: 'Replication Factor',
        type: 'number',
        default: 3,
        min: 3,
        max: 5,
        description: 'Raft replication factor',
      },
    ],
  },
  {
    id: 'generic_high_perf_wide_column',
    display_name: 'High-Perf Wide-Column',
    category: ComponentCategory.Database,
    generic_equivalent: 'generic_cassandra',
    capacity: { max_rps: 200000, latency_p50_ms: 0.5, latency_p99_ms: 5 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'C++ Cassandra-compatible; very flat saturation curve',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_shard_count: 1000, max_memory_gb: 2048 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Shard Imbalance',
        trigger_condition: 'token ring imbalance > 30%',
        impact: 'hot shards throttle, cold shards idle',
        recovery_time_ms: 0,
      },
      {
        name: 'Commitlog Overflow',
        trigger_condition: 'write rate > commitlog flush rate',
        impact: 'writes stall',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'scylladb',
    properties: [
      {
        key: 'node_count',
        label: 'Node Count',
        type: 'number',
        default: 3,
        min: 3,
        max: 100,
        description: 'Cluster node count',
      },
      {
        key: 'shards_per_core',
        label: 'Shards Per Core',
        type: 'number',
        default: 4,
        min: 1,
        max: 16,
        description: 'ScyllaDB shards per CPU core',
      },
      {
        key: 'replication_factor',
        label: 'Replication Factor',
        type: 'number',
        default: 3,
        min: 1,
        max: 5,
        description: 'Data replication factor',
      },
    ],
  },
  {
    id: 'generic_serverless_db',
    display_name: 'Serverless DB',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.5],
      description: 'Auto-scales compute; cold starts dominate tail latency',
    },
    cold_start: { base_latency_ms: 500, runtime_overrides: {}, vpc_penalty_ms: 100 },
    throttle_behaviour: 'queue',
    limits: { max_document_size_mb: 8, max_indexes_per_collection: 64 },
    az_config: null,
    failure_modes: [
      {
        name: 'Cold Start',
        trigger_condition: 'idle period > 5min',
        impact: 'first query latency spike 500ms+',
        recovery_time_ms: 0,
      },
      {
        name: 'Throughput Throttle',
        trigger_condition: 'rps > provisioned throughput',
        impact: 'requests queued with increased latency',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'read unit', base_cost_usd: 0.00000025, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'app_server',
    properties: [
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        default: 'us-east-1',
        options: ['us-east-1', 'eu-west-1', 'ap-southeast-1'],
        description: 'Deployment region',
      },
      {
        key: 'indexes',
        label: 'Indexes',
        type: 'number',
        default: 3,
        min: 0,
        max: 64,
        description: 'Number of collection indexes',
      },
      {
        key: 'strict_schema',
        label: 'Schema Enforcement',
        type: 'boolean',
        default: false,
        description: 'Enforce document schema validation',
      },
    ],
  },
  {
    id: 'generic_newsql_db',
    display_name: 'NewSQL DB',
    category: ComponentCategory.Database,
    generic_equivalent: 'generic_mysql',
    capacity: { max_rps: 15000, latency_p50_ms: 8, latency_p99_ms: 80 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_nodes: 1000, max_storage_pb: 5 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Raft Quorum Loss',
        trigger_condition: 'majority nodes unavailable',
        impact: 'write unavailability until quorum restored',
        recovery_time_ms: 30000,
      },
      {
        name: 'Region Failover',
        trigger_condition: 'primary region failure',
        impact: '15–60s failover to secondary region',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'tidb',
    properties: [
      {
        key: 'tidb_nodes',
        label: 'TiDB Nodes',
        type: 'number',
        default: 3,
        min: 1,
        max: 100,
        description: 'SQL compute layer nodes',
      },
      {
        key: 'tikv_nodes',
        label: 'TiKV Nodes',
        type: 'number',
        default: 3,
        min: 3,
        max: 200,
        description: 'Key-value storage nodes',
      },
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 3,
        min: 1,
        max: 5,
        description: 'Data replicas per region',
      },
    ],
  },
  {
    id: 'generic_data_warehouse',
    display_name: 'Data Warehouse',
    category: ComponentCategory.Database,
    generic_equivalent: null,
    capacity: { max_rps: 50, latency_p50_ms: 2000, latency_p99_ms: 60000 },
    saturation_curve: {
      coefficients: [1, 1.5, 6.0],
      description: 'Concurrent large scans compete for I/O and compute slots',
    },
    cold_start: { base_latency_ms: 5000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'queue',
    limits: { max_concurrent_queries: 50, max_query_execution_time_s: 3600 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Slot Contention',
        trigger_condition: 'concurrent_queries > max_slots',
        impact: 'queries queue indefinitely',
        recovery_time_ms: 0,
      },
      {
        name: 'Long-Running Query',
        trigger_condition: 'query_runtime > max_execution_time',
        impact: 'query killed, wasted compute',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'TB scanned', base_cost_usd: 5, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'bigquery',
    properties: [
      {
        key: 'cluster_size',
        label: 'Cluster Size',
        type: 'select',
        default: 'medium',
        options: ['x-small', 'small', 'medium', 'large', 'x-large', '2x-large', '4x-large'],
        description: 'Warehouse compute size',
      },
      {
        key: 'auto_suspend_s',
        label: 'Auto-Suspend',
        type: 'number',
        default: 300,
        min: 60,
        max: 3600,
        unit: 's',
        description: 'Auto-suspend after N seconds of inactivity',
      },
      {
        key: 'query_timeout_s',
        label: 'Query Timeout',
        type: 'number',
        default: 600,
        min: 30,
        max: 3600,
        unit: 's',
        description: 'Maximum query execution time',
      },
    ],
  },
];
