import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};

export const messagingComponents: CBREntry[] = [
  {
    id: 'generic_kafka',
    display_name: 'Apache Kafka',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 1000000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'Scales linearly with partitions; disk I/O eventually limits',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_message_size_mb: 1, default_retention_days: 7, max_partitions_per_broker: 2000 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Leader Election Delay',
        trigger_condition: 'broker failure triggers partition re-election',
        impact: 'produce/consume pause during re-election (seconds)',
        recovery_time_ms: 30000,
      },
      {
        name: 'Consumer Lag Explosion',
        trigger_condition: 'consumer processing slower than produce rate',
        impact: 'unbounded lag; eventual message loss at retention boundary',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'kafka',
    properties: [
      {
        key: 'broker_count',
        label: 'Broker Count',
        type: 'number',
        default: 3,
        min: 1,
        max: 100,
        description: 'Number of Kafka brokers',
      },
      {
        key: 'partitions',
        label: 'Default Partitions',
        type: 'number',
        default: 10,
        min: 1,
        max: 1000,
        description: 'Default partitions per topic',
      },
      {
        key: 'replication_factor',
        label: 'Replication Factor',
        type: 'number',
        default: 3,
        min: 1,
        max: 5,
        description: 'Topic replication factor',
      },
      {
        key: 'retention_days',
        label: 'Retention',
        type: 'number',
        default: 7,
        min: 1,
        max: 365,
        unit: 'days',
        description: 'Message retention period',
      },
    ],
  },
  {
    id: 'generic_rabbitmq',
    display_name: 'RabbitMQ',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_queues: 10000, max_message_size_mb: 2 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Memory Alarm',
        trigger_condition: 'broker memory > memory_high_watermark',
        impact: 'publishing blocked; consumers can still drain',
        recovery_time_ms: 30000,
      },
      {
        name: 'Split-Brain',
        trigger_condition: 'network partition in mirrored queue cluster',
        impact: 'queue replicas diverge; messages potentially duplicated/lost',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'rabbitmq',
    properties: [
      {
        key: 'nodes',
        label: 'Cluster Nodes',
        type: 'number',
        default: 3,
        min: 1,
        max: 9,
        description: 'RabbitMQ cluster node count',
      },
      {
        key: 'queue_type',
        label: 'Queue Type',
        type: 'select',
        default: 'quorum',
        options: ['classic', 'quorum', 'stream'],
        description: 'Default queue type',
      },
      {
        key: 'prefetch_count',
        label: 'Prefetch Count',
        type: 'number',
        default: 10,
        min: 1,
        max: 1000,
        description: 'Consumer prefetch count (QoS)',
      },
    ],
  },
  {
    id: 'generic_message_queue',
    display_name: 'Message Queue',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 3000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_message_size_kb: 256, max_retention_days: 4 },
    az_config: null,
    failure_modes: [
      {
        name: 'Visibility Timeout Exceeded',
        trigger_condition: 'consumer processing time > visibility_timeout',
        impact: 'message redelivered; duplicate processing',
        recovery_time_ms: 0,
      },
      {
        name: 'Queue Depth Explosion',
        trigger_condition: 'producers overwhelm consumers',
        impact: 'processing latency grows; messages expire if retention exceeded',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'million requests', base_cost_usd: 0.4, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'queue',
    properties: [
      {
        key: 'visibility_timeout_s',
        label: 'Visibility Timeout',
        type: 'number',
        default: 30,
        min: 1,
        max: 43200,
        unit: 's',
        description: 'Time a message is invisible after receive',
      },
      {
        key: 'message_retention_days',
        label: 'Retention',
        type: 'number',
        default: 4,
        min: 1,
        max: 14,
        unit: 'days',
        description: 'Message retention period',
      },
      {
        key: 'delay_seconds',
        label: 'Delivery Delay',
        type: 'number',
        default: 0,
        min: 0,
        max: 900,
        unit: 's',
        description: 'Message delivery delay',
      },
    ],
  },
  {
    id: 'generic_event_bus',
    display_name: 'Event Bus',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_rules_per_bus: 300, max_targets_per_rule: 5 },
    az_config: null,
    failure_modes: [
      {
        name: 'Rule Evaluation Throttle',
        trigger_condition: 'events/s > put_events_quota',
        impact: 'events throttled with ThrottlingException',
        recovery_time_ms: 0,
      },
      {
        name: 'Dead Letter Queue Overflow',
        trigger_condition: 'target delivery failures > retry limit',
        impact: 'events lost if DLQ not configured',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'million events', base_cost_usd: 1.0, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'event_bus',
    properties: [
      {
        key: 'target_count',
        label: 'Targets',
        type: 'number',
        default: 3,
        min: 1,
        max: 5,
        description: 'Number of event targets per rule',
      },
      {
        key: 'retry_attempts',
        label: 'Retry Attempts',
        type: 'number',
        default: 3,
        min: 0,
        max: 185,
        description: 'Target invocation retry attempts',
      },
      {
        key: 'dlq_enabled',
        label: 'Dead Letter Queue',
        type: 'boolean',
        default: true,
        description: 'Route failed events to DLQ',
      },
    ],
  },
  {
    id: 'generic_dlq',
    display_name: 'Dead Letter Queue',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 1000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_message_size_kb: 256, max_retention_days: 14 },
    az_config: null,
    failure_modes: [
      {
        name: 'DLQ Full',
        trigger_condition: 'messages in DLQ > storage limit',
        impact: 'failed messages dropped; lost forever',
        recovery_time_ms: 0,
      },
      {
        name: 'Poison Pill',
        trigger_condition: 'unprocessable message loops back to DLQ',
        impact: 'DLQ fills rapidly; alerts needed',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'million requests', base_cost_usd: 0.4, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'queue',
    properties: [
      {
        key: 'max_receive_count',
        label: 'Max Receive Count',
        type: 'number',
        default: 3,
        min: 1,
        max: 1000,
        description: 'Failures before message sent to DLQ',
      },
      {
        key: 'retention_days',
        label: 'Retention',
        type: 'number',
        default: 14,
        min: 1,
        max: 14,
        unit: 'days',
        description: 'DLQ message retention',
      },
      {
        key: 'alarm_threshold',
        label: 'Alarm Threshold',
        type: 'number',
        default: 1,
        min: 1,
        max: 1000000,
        description: 'Alert when message count exceeds this',
      },
    ],
  },
  {
    id: 'generic_websocket_broker',
    display_name: 'WebSocket Broker',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 100000, latency_p50_ms: 5, latency_p99_ms: 30 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_connections: 500000, max_message_size_kb: 128 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Connection Broadcast Storm',
        trigger_condition: 'broadcast message to all N connections',
        impact: 'O(N) CPU and bandwidth; broker saturated',
        recovery_time_ms: 0,
      },
      {
        name: 'Broker Restart',
        trigger_condition: 'OOM or crash',
        impact: 'all active WebSocket connections dropped',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: { unit: 'million messages', base_cost_usd: 1.0, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'queue',
    properties: [
      {
        key: 'max_connections',
        label: 'Max Connections',
        type: 'number',
        default: 100000,
        min: 1000,
        max: 10000000,
        description: 'Max concurrent WebSocket connections',
      },
      {
        key: 'channel_auth',
        label: 'Channel Auth',
        type: 'boolean',
        default: true,
        description: 'Authenticate channel subscriptions',
      },
      {
        key: 'presence',
        label: 'Presence Channels',
        type: 'boolean',
        default: false,
        description: 'Enable online presence tracking',
      },
    ],
  },
  {
    id: 'generic_pulsar',
    display_name: 'Apache Pulsar',
    category: ComponentCategory.Messaging,
    generic_equivalent: 'generic_kafka',
    capacity: { max_rps: 500000, latency_p50_ms: 5, latency_p99_ms: 30 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'Tiered storage offloads to object store; stable under sustained load',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_message_size_mb: 5, max_topics: 1000000 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'BookKeeper Bookie Failure',
        trigger_condition: 'bookie node fails',
        impact: 'ledger segment re-replication; publish latency spikes',
        recovery_time_ms: 30000,
      },
      {
        name: 'Geo-Replication Lag',
        trigger_condition: 'cross-region bandwidth saturated',
        impact: 'replication lag; secondary region reads stale data',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'pulsar',
    properties: [
      {
        key: 'brokers',
        label: 'Brokers',
        type: 'number',
        default: 3,
        min: 1,
        max: 50,
        description: 'Number of Pulsar brokers',
      },
      {
        key: 'bookies',
        label: 'BookKeeper Bookies',
        type: 'number',
        default: 3,
        min: 3,
        max: 50,
        description: 'Number of BookKeeper storage nodes',
      },
      {
        key: 'tiered_storage',
        label: 'Tiered Storage',
        type: 'boolean',
        default: false,
        description: 'Offload old segments to object storage',
      },
    ],
  },
  {
    id: 'generic_redis_streams',
    display_name: 'Redis Streams',
    category: ComponentCategory.Messaging,
    generic_equivalent: 'generic_kafka',
    capacity: { max_rps: 100000, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: {
      coefficients: [1, 0.2, 1.5],
      description: 'Memory-bound; latency flat until memory pressure',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_stream_length: 10000000, max_message_size_kb: 512 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Stream Memory Overflow',
        trigger_condition: 'stream grows beyond maxlen',
        impact: 'old entries evicted if MAXLEN set; otherwise Redis OOM',
        recovery_time_ms: 0,
      },
      {
        name: 'Replication Lag',
        trigger_condition: 'replica falls behind primary',
        impact: 'consumer group on replica reads stale messages',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'redis',
    properties: [
      {
        key: 'max_len',
        label: 'Max Stream Length',
        type: 'number',
        default: 0,
        min: 0,
        max: 10000000,
        description: 'Max entries (0 = unlimited)',
      },
      {
        key: 'consumer_groups',
        label: 'Consumer Groups',
        type: 'number',
        default: 1,
        min: 1,
        max: 100,
        description: 'Number of consumer groups',
      },
      {
        key: 'persistence',
        label: 'Persistence',
        type: 'select',
        default: 'rdb',
        options: ['none', 'rdb', 'aof'],
        description: 'Stream persistence mode',
      },
    ],
  },
  {
    id: 'generic_event_sourcing_store',
    display_name: 'Event Sourcing Store',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 10, latency_p99_ms: 80 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_stream_size_gb: 1000, max_event_size_kb: 64 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Snapshot Gap',
        trigger_condition: 'aggregate with millions of events, no snapshot',
        impact: 'aggregate replay extremely slow on load',
        recovery_time_ms: 0,
      },
      {
        name: 'Concurrent Write Conflict',
        trigger_condition: 'two writers append to same stream simultaneously',
        impact: 'optimistic concurrency conflict; one writer must retry',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'event_bus',
    properties: [
      {
        key: 'snapshot_interval',
        label: 'Snapshot Interval',
        type: 'number',
        default: 100,
        min: 0,
        max: 10000,
        unit: 'events',
        description: 'Snapshot aggregate every N events (0=disabled)',
      },
      {
        key: 'projections',
        label: 'Live Projections',
        type: 'boolean',
        default: true,
        description: 'Enable real-time event projections',
      },
      {
        key: 'retention_days',
        label: 'Retention',
        type: 'number',
        default: 365,
        min: 30,
        max: 3650,
        unit: 'days',
        description: 'Event retention period',
      },
    ],
  },
  {
    id: 'generic_cqrs_bus',
    display_name: 'CQRS Command Bus',
    category: ComponentCategory.Messaging,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 15, latency_p99_ms: 100 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_command_size_kb: 64, max_handlers_per_command: 1 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Command Handler Timeout',
        trigger_condition: 'handler takes > configured timeout',
        impact: 'command fails; client may retry; idempotency required',
        recovery_time_ms: 0,
      },
      {
        name: 'Read Model Staleness',
        trigger_condition: 'projector lagging behind command writes',
        impact: 'queries return stale data',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'event_bus',
    properties: [
      {
        key: 'async_commands',
        label: 'Async Commands',
        type: 'boolean',
        default: false,
        description: 'Process commands asynchronously',
      },
      {
        key: 'command_timeout_ms',
        label: 'Command Timeout',
        type: 'number',
        default: 5000,
        min: 100,
        max: 60000,
        unit: 'ms',
        description: 'Max command processing time',
      },
      {
        key: 'idempotency',
        label: 'Idempotency Keys',
        type: 'boolean',
        default: true,
        description: 'Enable idempotent command deduplication',
      },
    ],
  },
];
