import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};

export const networkingComponents: CBREntry[] = [
  {
    id: 'generic_load_balancer_l4',
    display_name: 'Load Balancer (L4)',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 1000000, latency_p50_ms: 0.1, latency_p99_ms: 1 },
    saturation_curve: {
      coefficients: [1, 0.02, 0.3],
      description: 'Very flat; kernel-level packet forwarding',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_connections: 10000000, max_bandwidth_gbps: 100 },
    az_config: { min_az: 2, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Connection Table Overflow',
        trigger_condition: 'active_connections >= max_connections',
        impact: 'new connections dropped',
        recovery_time_ms: 0,
      },
      {
        name: 'Backend Failure',
        trigger_condition: 'all healthy backends = 0',
        impact: 'all requests fail with 503',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: { unit: 'hour', base_cost_usd: 0.008, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'load_balancer',
    properties: [
      {
        key: 'algorithm',
        label: 'Algorithm',
        type: 'select',
        default: 'round_robin',
        options: ['round_robin', 'least_connections', 'ip_hash', 'random'],
        description: 'Load balancing algorithm',
      },
      {
        key: 'health_check_interval_s',
        label: 'Health Check Interval',
        type: 'number',
        default: 10,
        min: 1,
        max: 300,
        unit: 's',
        description: 'Backend health check interval',
      },
      {
        key: 'connection_draining_s',
        label: 'Connection Draining',
        type: 'number',
        default: 30,
        min: 0,
        max: 3600,
        unit: 's',
        description: 'Draining timeout before deregistering backend',
      },
    ],
  },
  {
    id: 'generic_load_balancer_l7',
    display_name: 'Load Balancer (L7)',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 100000, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_connections: 1000000, max_rules: 100, max_target_groups: 100 },
    az_config: { min_az: 2, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'SSL Handshake Exhaustion',
        trigger_condition: 'new TLS connections overwhelm termination capacity',
        impact: 'latency spike; connection timeouts',
        recovery_time_ms: 5000,
      },
      {
        name: 'Rule Evaluation Overhead',
        trigger_condition: 'complex routing rules at high rps',
        impact: 'added per-request latency',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'hour', base_cost_usd: 0.018, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'load_balancer',
    properties: [
      {
        key: 'algorithm',
        label: 'Algorithm',
        type: 'select',
        default: 'round_robin',
        options: ['round_robin', 'least_outstanding_requests', 'weighted'],
        description: 'Load balancing algorithm',
      },
      {
        key: 'sticky_sessions',
        label: 'Sticky Sessions',
        type: 'boolean',
        default: false,
        description: 'Enable cookie-based session stickiness',
      },
      {
        key: 'waf_enabled',
        label: 'WAF Enabled',
        type: 'boolean',
        default: false,
        description: 'Attach Web Application Firewall',
      },
      {
        key: 'tls_policy',
        label: 'TLS Policy',
        type: 'select',
        default: 'TLS-1-2',
        options: ['TLS-1-0', 'TLS-1-1', 'TLS-1-2', 'TLS-1-3'],
        description: 'Minimum TLS version',
      },
    ],
  },
  {
    id: 'generic_api_gateway',
    display_name: 'API Gateway',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 5, latency_p99_ms: 30 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { default_burst_limit: 5000, default_rate_limit_rps: 10000, max_payload_mb: 10 },
    az_config: null,
    failure_modes: [
      {
        name: 'Throttle Cascade',
        trigger_condition: 'rps exceeds account-level quota',
        impact: '429 responses; client retries amplify load',
        recovery_time_ms: 60000,
      },
      {
        name: 'Integration Timeout',
        trigger_condition: 'backend response > gateway timeout',
        impact: '504 returned to client; backend still processing',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'million calls', base_cost_usd: 3.5, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'api_gateway',
    properties: [
      {
        key: 'rate_limit_rps',
        label: 'Rate Limit',
        type: 'number',
        default: 1000,
        min: 1,
        max: 100000,
        unit: 'req/s',
        description: 'Global rate limit per API key',
      },
      {
        key: 'timeout_ms',
        label: 'Integration Timeout',
        type: 'number',
        default: 29000,
        min: 50,
        max: 29000,
        unit: 'ms',
        description: 'Max backend integration timeout',
      },
      {
        key: 'caching',
        label: 'Response Cache',
        type: 'boolean',
        default: false,
        description: 'Enable API response caching',
      },
      {
        key: 'auth_type',
        label: 'Auth Type',
        type: 'select',
        default: 'none',
        options: ['none', 'api_key', 'jwt', 'iam', 'cognito'],
        description: 'API authentication method',
      },
    ],
  },
  {
    id: 'generic_cdn',
    display_name: 'CDN',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 10000000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: {
      coefficients: [1, 0.01, 0.1],
      description: 'Globally distributed PoPs; effectively unlimited with high cache hit rate',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_bandwidth_tbps: 100, default_ttl_s: 86400 },
    az_config: null,
    failure_modes: [
      {
        name: 'Cache Miss Storm',
        trigger_condition: 'cache invalidation or cold PoP',
        impact: 'origin overwhelmed with requests; latency spikes',
        recovery_time_ms: 60000,
      },
      {
        name: 'BGP Routing Issue',
        trigger_condition: 'anycast routing failure at PoP',
        impact: 'traffic rerouted to farther PoP, latency increase',
        recovery_time_ms: 300000,
      },
    ],
    cost_model: { unit: 'GB transfer', base_cost_usd: 0.085, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'cloudfront',
    properties: [
      {
        key: 'ttl_s',
        label: 'Default TTL',
        type: 'number',
        default: 86400,
        min: 0,
        max: 31536000,
        unit: 's',
        description: 'Default cache TTL',
      },
      {
        key: 'compression',
        label: 'Compression',
        type: 'boolean',
        default: true,
        description: 'Enable gzip/brotli compression',
      },
      {
        key: 'https_only',
        label: 'HTTPS Only',
        type: 'boolean',
        default: true,
        description: 'Redirect HTTP to HTTPS',
      },
      {
        key: 'geo_restriction',
        label: 'Geo Restriction',
        type: 'boolean',
        default: false,
        description: 'Enable geographic access control',
      },
    ],
  },
  {
    id: 'generic_dns',
    display_name: 'DNS',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 1, latency_p99_ms: 20 },
    saturation_curve: {
      coefficients: [1, 0.05, 0.3],
      description: 'Highly cached; resolver throughput rarely a bottleneck',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_records_per_zone: 10000, default_ttl_s: 300 },
    az_config: null,
    failure_modes: [
      {
        name: 'TTL Propagation Delay',
        trigger_condition: 'DNS record change with high TTL',
        impact: 'old record cached for TTL duration; traffic to wrong endpoint',
        recovery_time_ms: 300000,
      },
      {
        name: 'NXDOMAIN Flood',
        trigger_condition: 'random subdomain DDoS',
        impact: 'authoritative server CPU saturated',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'million queries', base_cost_usd: 0.4, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'dns',
    properties: [
      {
        key: 'ttl_s',
        label: 'Default TTL',
        type: 'number',
        default: 300,
        min: 1,
        max: 86400,
        unit: 's',
        description: 'Default record TTL',
      },
      {
        key: 'routing_policy',
        label: 'Routing Policy',
        type: 'select',
        default: 'simple',
        options: ['simple', 'weighted', 'latency', 'failover', 'geolocation'],
        description: 'DNS routing policy',
      },
      {
        key: 'health_check',
        label: 'Health Check',
        type: 'boolean',
        default: false,
        description: 'Enable DNS health checks for failover',
      },
    ],
  },
  {
    id: 'generic_reverse_proxy',
    display_name: 'Reverse Proxy',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'Efficient proxying; flat curve until connection limit',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_connections: 100000, max_upstream_connections: 10000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Upstream Unavailable',
        trigger_condition: 'all upstream backends fail health check',
        impact: '502 Bad Gateway returned',
        recovery_time_ms: 10000,
      },
      {
        name: 'Buffer Overflow',
        trigger_condition: 'slow clients with large responses',
        impact: 'memory pressure; upstream held open',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'nginx',
    properties: [
      {
        key: 'caching',
        label: 'Response Caching',
        type: 'boolean',
        default: false,
        description: 'Cache upstream responses locally',
      },
      {
        key: 'ssl_termination',
        label: 'SSL Termination',
        type: 'boolean',
        default: true,
        description: 'Terminate TLS at proxy',
      },
      {
        key: 'buffer_size_kb',
        label: 'Buffer Size',
        type: 'number',
        default: 64,
        min: 4,
        max: 4096,
        unit: 'KB',
        description: 'Proxy buffer size per request',
      },
    ],
  },
  {
    id: 'generic_forward_proxy',
    display_name: 'Forward Proxy',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_connections: 50000, max_cached_objects_mb: 8192 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'DNS Poisoning',
        trigger_condition: 'malicious DNS response for proxied request',
        impact: 'clients directed to malicious endpoint',
        recovery_time_ms: 0,
      },
      {
        name: 'Cache Poisoning',
        trigger_condition: 'malicious content cached via shared key',
        impact: 'all clients receive malicious response',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'load_balancer',
    properties: [
      {
        key: 'caching',
        label: 'Caching',
        type: 'boolean',
        default: true,
        description: 'Cache outbound responses',
      },
      {
        key: 'filtering',
        label: 'URL Filtering',
        type: 'boolean',
        default: false,
        description: 'Enable outbound URL filtering/blocking',
      },
      {
        key: 'ssl_inspection',
        label: 'SSL Inspection',
        type: 'boolean',
        default: false,
        description: 'Enable HTTPS inspection (MITM)',
      },
    ],
  },
  {
    id: 'generic_service_mesh',
    display_name: 'Service Mesh',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 100000, latency_p50_ms: 1, latency_p99_ms: 5 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.5],
      description: 'Sidecar overhead fixed ~0.5–1ms per hop',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_services: 1000, control_plane_cpu_per_1000_rps: 0.1 },
    az_config: { min_az: 3, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Control Plane Overload',
        trigger_condition: 'config push rate > control plane capacity',
        impact: 'stale routing config; envoy proxy uses old rules',
        recovery_time_ms: 30000,
      },
      {
        name: 'mTLS Certificate Expiry',
        trigger_condition: 'cert rotation fails silently',
        impact: 'inter-service traffic blocked',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'istio',
    properties: [
      {
        key: 'mtls',
        label: 'mTLS',
        type: 'boolean',
        default: true,
        description: 'Enforce mutual TLS between services',
      },
      {
        key: 'tracing',
        label: 'Distributed Tracing',
        type: 'boolean',
        default: true,
        description: 'Enable trace context propagation',
      },
      {
        key: 'circuit_breaker',
        label: 'Circuit Breaker',
        type: 'boolean',
        default: true,
        description: 'Enable outlier detection circuit breaking',
      },
      {
        key: 'retries',
        label: 'Automatic Retries',
        type: 'number',
        default: 2,
        min: 0,
        max: 5,
        description: 'Automatic retry count on 5xx',
      },
    ],
  },
  {
    id: 'generic_vpn_gateway',
    display_name: 'VPN Gateway',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 1000, latency_p50_ms: 5, latency_p99_ms: 30 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_tunnels: 1000, max_bandwidth_gbps: 10 },
    az_config: { min_az: 2, max_az: 2, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Tunnel Flap',
        trigger_condition: 'BGP session instability or NAT timeout',
        impact: 'tunnel re-establishment; seconds to minutes of downtime',
        recovery_time_ms: 30000,
      },
      {
        name: 'Bandwidth Saturation',
        trigger_condition: 'throughput >= max_bandwidth_gbps',
        impact: 'packet loss and increased latency',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'hour', base_cost_usd: 0.05, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'vpn',
    properties: [
      {
        key: 'protocol',
        label: 'Protocol',
        type: 'select',
        default: 'IPsec',
        options: ['IPsec', 'OpenVPN', 'WireGuard', 'GRE'],
        description: 'VPN tunnel protocol',
      },
      {
        key: 'ha_mode',
        label: 'High Availability',
        type: 'boolean',
        default: true,
        description: 'Active-standby HA configuration',
      },
      {
        key: 'bgp',
        label: 'BGP Routing',
        type: 'boolean',
        default: true,
        description: 'Enable dynamic BGP routing',
      },
    ],
  },
  {
    id: 'generic_nat_gateway',
    display_name: 'NAT Gateway',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 1000000, latency_p50_ms: 0.5, latency_p99_ms: 3 },
    saturation_curve: {
      coefficients: [1, 0.05, 0.5],
      description: 'Managed service; scales automatically per AZ',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_connections: 55000, max_bandwidth_gbps: 45 },
    az_config: { min_az: 1, max_az: 1, cross_az_latency_ms: 0 },
    failure_modes: [
      {
        name: 'Connection Tracking Limit',
        trigger_condition: 'simultaneous connections >= max_connections',
        impact: 'new outbound connections drop',
        recovery_time_ms: 0,
      },
      {
        name: 'AZ Failure',
        trigger_condition: 'AZ where NAT gateway resides fails',
        impact: 'all private subnet outbound traffic in that AZ drops',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: { unit: 'GB processed', base_cost_usd: 0.045, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'nat',
    properties: [
      {
        key: 'per_az',
        label: 'One per AZ',
        type: 'boolean',
        default: true,
        description: 'Deploy NAT gateway in each AZ for resilience',
      },
      {
        key: 'elastic_ip_count',
        label: 'Elastic IPs',
        type: 'number',
        default: 1,
        min: 1,
        max: 8,
        description: 'Number of elastic IPs (outbound addresses)',
      },
    ],
  },
  {
    id: 'generic_firewall_waf',
    display_name: 'Firewall / WAF',
    category: ComponentCategory.Networking,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_rules: 1500, max_ip_set_size: 10000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'False Positive Block',
        trigger_condition: 'legitimate traffic matches WAF rule',
        impact: 'valid users blocked; 403 errors',
        recovery_time_ms: 0,
      },
      {
        name: 'Rule Evaluation Latency',
        trigger_condition: 'large rule set applied to high rps',
        impact: 'added per-request latency',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'million requests', base_cost_usd: 0.6, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'firewall',
    properties: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'select',
        default: 'block',
        options: ['count', 'block'],
        description: 'WAF action mode',
      },
      {
        key: 'managed_rules',
        label: 'Managed Rule Groups',
        type: 'boolean',
        default: true,
        description: 'Enable cloud provider managed WAF rules',
      },
      {
        key: 'rate_limiting',
        label: 'Rate Limiting',
        type: 'boolean',
        default: true,
        description: 'Enable IP-based rate limiting',
      },
      {
        key: 'sql_injection',
        label: 'SQLi Protection',
        type: 'boolean',
        default: true,
        description: 'Enable SQL injection detection',
      },
    ],
  },
  {
    id: 'generic_ingress_controller',
    display_name: 'Ingress Controller',
    category: ComponentCategory.Networking,
    generic_equivalent: 'generic_reverse_proxy',
    capacity: { max_rps: 100000, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: QUAD_CURVE,
    cold_start: { base_latency_ms: 3000, runtime_overrides: {}, vpc_penalty_ms: 0 },
    throttle_behaviour: 'shed',
    limits: { max_ingress_rules: 1000, max_tls_certs: 100 },
    az_config: { min_az: 2, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Controller Pod Crash',
        trigger_condition: 'ingress controller pod fails',
        impact: 'no new ingress rule reconciliation; existing routes may still work',
        recovery_time_ms: 30000,
      },
      {
        name: 'Config Reconciliation Lag',
        trigger_condition: 'many simultaneous ingress resource changes',
        impact: 'new routes delayed up to seconds',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'nginx',
    properties: [
      {
        key: 'class',
        label: 'Ingress Class',
        type: 'select',
        default: 'nginx',
        options: ['nginx', 'traefik', 'haproxy', 'istio', 'aws-alb'],
        description: 'Ingress controller implementation',
      },
      {
        key: 'replicas',
        label: 'Replicas',
        type: 'number',
        default: 2,
        min: 1,
        max: 20,
        description: 'Controller pod replicas',
      },
      {
        key: 'tls_termination',
        label: 'TLS Termination',
        type: 'boolean',
        default: true,
        description: 'Terminate TLS at ingress',
      },
    ],
  },
];
