import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};

export const observabilityComponents: CBREntry[] = [
  {
    id: 'generic_prometheus',
    display_name: 'Prometheus',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 1000000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: {
      coefficients: [1, 0.3, 3.0],
      description: 'TSDB compaction and high cardinality degrade performance steeply',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_active_series: 2000000, max_scrape_interval_s: 60 },
    az_config: { min_az: 1, max_az: 1, cross_az_latency_ms: 0 },
    failure_modes: [
      {
        name: 'Cardinality Explosion',
        trigger_condition: 'unique series > max_active_series',
        impact: 'OOM; Prometheus crashes',
        recovery_time_ms: 30000,
      },
      {
        name: 'Scrape Overload',
        trigger_condition: 'too many targets with short scrape intervals',
        impact: 'CPU saturated; scrapes time out; data gaps',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'prometheus',
    properties: [
      {
        key: 'scrape_interval_s',
        label: 'Scrape Interval',
        type: 'number',
        default: 15,
        min: 1,
        max: 300,
        unit: 's',
        description: 'How often to scrape metrics',
      },
      {
        key: 'retention_days',
        label: 'Retention',
        type: 'number',
        default: 15,
        min: 1,
        max: 365,
        unit: 'days',
        description: 'TSDB retention period',
      },
      {
        key: 'ha_mode',
        label: 'HA Mode',
        type: 'boolean',
        default: false,
        description: 'Run two identical Prometheus instances for HA',
      },
      {
        key: 'remote_write',
        label: 'Remote Write',
        type: 'boolean',
        default: false,
        description: 'Stream metrics to remote long-term storage',
      },
    ],
  },
  {
    id: 'generic_grafana',
    display_name: 'Grafana',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 100, latency_p99_ms: 1000 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_dashboards: 10000, max_users: 50000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Heavy Dashboard Query',
        trigger_condition: 'dashboard with many panels triggers N data source queries',
        impact: 'data source overloaded; dashboard load times spike',
        recovery_time_ms: 30000,
      },
      {
        name: 'Database Connection Loss',
        trigger_condition: 'Grafana DB (SQLite/Postgres/MySQL) unreachable',
        impact: 'UI unavailable; dashboards not loadable',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'grafana',
    properties: [
      {
        key: 'database',
        label: 'Backend DB',
        type: 'select',
        default: 'sqlite',
        options: ['sqlite', 'postgresql', 'mysql'],
        description: 'Grafana configuration database',
      },
      {
        key: 'auth_provider',
        label: 'Auth Provider',
        type: 'select',
        default: 'builtin',
        options: ['builtin', 'oauth', 'ldap', 'saml'],
        description: 'Authentication provider',
      },
      {
        key: 'alerting',
        label: 'Unified Alerting',
        type: 'boolean',
        default: true,
        description: 'Enable Grafana unified alerting',
      },
    ],
  },
  {
    id: 'generic_metrics_collector',
    display_name: 'Metrics Collector',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 500000, latency_p50_ms: 1, latency_p99_ms: 10 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'Agent-based; memory bounded by buffer size',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_metrics_per_second: 500000, buffer_size_mb: 512 },
    az_config: null,
    failure_modes: [
      {
        name: 'Buffer Overflow',
        trigger_condition: 'ingest rate > export rate sustained',
        impact: 'oldest metrics dropped; data gaps in dashboards',
        recovery_time_ms: 0,
      },
      {
        name: 'Backend Unavailable',
        trigger_condition: 'metrics sink (Prometheus/Datadog) unreachable',
        impact: 'metrics buffered until full, then dropped',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'prometheus',
    properties: [
      {
        key: 'agent',
        label: 'Agent Type',
        type: 'select',
        default: 'telegraf',
        options: ['telegraf', 'vector', 'otel_collector', 'datadog_agent'],
        description: 'Metrics collection agent',
      },
      {
        key: 'flush_interval_s',
        label: 'Flush Interval',
        type: 'number',
        default: 10,
        min: 1,
        max: 300,
        unit: 's',
        description: 'How often to flush metrics to backend',
      },
      {
        key: 'buffer_mb',
        label: 'Buffer Size',
        type: 'number',
        default: 64,
        min: 1,
        max: 1024,
        unit: 'MB',
        description: 'In-memory buffer before backend write',
      },
    ],
  },
  {
    id: 'generic_log_aggregator',
    display_name: 'Log Aggregator',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 100000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_ingest_gb_per_day: 10000, max_retention_days: 365 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Ingest Overflow',
        trigger_condition: 'log volume > ingest capacity',
        impact: 'log lines dropped; lost observability',
        recovery_time_ms: 0,
      },
      {
        name: 'Hot Partition',
        trigger_condition: 'single service emitting high log volume',
        impact: 'index shard hotspot; query latency increases',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'GB ingested', base_cost_usd: 0.5, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'elasticsearch',
    properties: [
      {
        key: 'backend',
        label: 'Backend',
        type: 'select',
        default: 'elasticsearch',
        options: ['elasticsearch', 'loki', 'splunk', 'cloudwatch', 'datadog'],
        description: 'Log storage backend',
      },
      {
        key: 'retention_days',
        label: 'Retention',
        type: 'number',
        default: 30,
        min: 1,
        max: 365,
        unit: 'days',
        description: 'Log retention period',
      },
      {
        key: 'structured_logging',
        label: 'Structured Logs',
        type: 'boolean',
        default: true,
        description: 'Parse and index structured JSON logs',
      },
    ],
  },
  {
    id: 'generic_distributed_tracing',
    display_name: 'Distributed Tracing',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 100000, latency_p50_ms: 5, latency_p99_ms: 50 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_spans_per_trace: 10000, max_trace_size_mb: 50 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Sampling Gap',
        trigger_condition: 'head-based sampling drops important traces',
        impact: 'production incidents hard to debug; key traces missing',
        recovery_time_ms: 0,
      },
      {
        name: 'Trace Store Overload',
        trigger_condition: 'trace ingest > store capacity',
        impact: 'traces dropped; reduced observability under load',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'million spans', base_cost_usd: 1.5, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'jaeger',
    properties: [
      {
        key: 'backend',
        label: 'Backend',
        type: 'select',
        default: 'jaeger',
        options: ['jaeger', 'zipkin', 'tempo', 'datadog', 'honeycomb', 'xray'],
        description: 'Tracing backend',
      },
      {
        key: 'sampling_rate',
        label: 'Sampling Rate',
        type: 'number',
        default: 0.1,
        min: 0.001,
        max: 1,
        description: 'Fraction of traces sampled (0.1 = 10%)',
      },
      {
        key: 'retention_days',
        label: 'Retention',
        type: 'number',
        default: 7,
        min: 1,
        max: 30,
        unit: 'days',
        description: 'Trace retention period',
      },
    ],
  },
  {
    id: 'generic_alerting_system',
    display_name: 'Alerting System',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 50, latency_p99_ms: 500 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_alert_rules: 10000, max_notification_channels: 100 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Alert Storm',
        trigger_condition: 'mass failure triggers thousands of alerts simultaneously',
        impact: 'notification channels overwhelmed; pages lost in noise',
        recovery_time_ms: 0,
      },
      {
        name: 'Alertmanager Silence Misconfiguration',
        trigger_condition: 'silence incorrectly applied during incident',
        impact: 'critical alerts suppressed; incident response delayed',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'grafana',
    properties: [
      {
        key: 'backend',
        label: 'Backend',
        type: 'select',
        default: 'alertmanager',
        options: ['alertmanager', 'pagerduty', 'opsgenie', 'victorops', 'grafana'],
        description: 'Alerting backend',
      },
      {
        key: 'grouping_window_s',
        label: 'Grouping Window',
        type: 'number',
        default: 30,
        min: 0,
        max: 300,
        unit: 's',
        description: 'Time to group related alerts before notifying',
      },
      {
        key: 'repeat_interval_h',
        label: 'Repeat Interval',
        type: 'number',
        default: 4,
        min: 1,
        max: 48,
        unit: 'h',
        description: 'Repeat alert notification interval',
      },
    ],
  },
  {
    id: 'generic_apm_agent',
    display_name: 'APM Agent',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 2, latency_p99_ms: 15 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.5],
      description: 'Sidecar overhead ~1–3% CPU; memory stable',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_transactions_per_minute: 3000000, max_overhead_pct: 5 },
    az_config: null,
    failure_modes: [
      {
        name: 'Agent Overhead Spike',
        trigger_condition: 'high rps + deep stack trace collection',
        impact: 'CPU overhead exceeds budget; service degradation',
        recovery_time_ms: 0,
      },
      {
        name: 'Agent OOM',
        trigger_condition: 'buffer fills when APM server unreachable',
        impact: 'agent disabled; no APM data until restart',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: { unit: 'host/month', base_cost_usd: 23, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'datadog',
    properties: [
      {
        key: 'vendor',
        label: 'APM Vendor',
        type: 'select',
        default: 'datadog',
        options: ['datadog', 'newrelic', 'dynatrace', 'elastic_apm', 'opentelemetry'],
        description: 'APM platform',
      },
      {
        key: 'profiling',
        label: 'Continuous Profiling',
        type: 'boolean',
        default: false,
        description: 'Enable continuous CPU/memory profiling',
      },
      {
        key: 'error_tracking',
        label: 'Error Tracking',
        type: 'boolean',
        default: true,
        description: 'Capture and group application errors',
      },
    ],
  },
  {
    id: 'generic_synthetic_monitor',
    display_name: 'Synthetic Monitor',
    category: ComponentCategory.Observability,
    generic_equivalent: null,
    capacity: { max_rps: 100, latency_p50_ms: 1000, latency_p99_ms: 5000 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.5],
      description: 'Generates synthetic load; not a bottleneck itself',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_monitors: 1000, min_check_interval_s: 60 },
    az_config: null,
    failure_modes: [
      {
        name: 'False Positive Alert',
        trigger_condition: 'transient network issue from probe location',
        impact: 'spurious alert; on-call woken unnecessarily',
        recovery_time_ms: 0,
      },
      {
        name: 'Probe Location Outage',
        trigger_condition: 'monitoring PoP fails',
        impact: 'checks from that region stop; uptime data gap',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: { unit: 'check/month', base_cost_usd: 0.001, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'datadog',
    properties: [
      {
        key: 'check_interval_s',
        label: 'Check Interval',
        type: 'number',
        default: 60,
        min: 60,
        max: 3600,
        unit: 's',
        description: 'How often to run synthetic check',
      },
      {
        key: 'locations',
        label: 'Probe Locations',
        type: 'number',
        default: 3,
        min: 1,
        max: 20,
        description: 'Number of geographic probe locations',
      },
      {
        key: 'alert_on_failure',
        label: 'Alert on Failure',
        type: 'boolean',
        default: true,
        description: 'Send alert when check fails',
      },
    ],
  },
];
