import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};

export const securityComponents: CBREntry[] = [
  {
    id: 'generic_auth_server',
    display_name: 'Auth Server',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 20, latency_p99_ms: 150 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_concurrent_sessions: 1000000, max_tokens_per_minute: 10000 },
    az_config: { min_az: 2, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'Token Signing Key Unavailable',
        trigger_condition: 'KMS/HSM unreachable',
        impact: 'no new tokens can be issued; existing tokens still valid',
        recovery_time_ms: 30000,
      },
      {
        name: 'Session Store Failure',
        trigger_condition: 'Redis/DB backing store for sessions down',
        impact: 'session validation fails; users logged out',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'security',
    properties: [
      {
        key: 'protocol',
        label: 'Protocol',
        type: 'select',
        default: 'oauth2',
        options: ['oauth2', 'oidc', 'saml', 'custom'],
        description: 'Authentication protocol',
      },
      {
        key: 'token_ttl_s',
        label: 'Token TTL',
        type: 'number',
        default: 3600,
        min: 60,
        max: 86400,
        unit: 's',
        description: 'Access token lifetime',
      },
      {
        key: 'refresh_token_ttl_days',
        label: 'Refresh Token TTL',
        type: 'number',
        default: 30,
        min: 1,
        max: 365,
        unit: 'days',
        description: 'Refresh token lifetime',
      },
      {
        key: 'mfa_required',
        label: 'MFA Required',
        type: 'boolean',
        default: false,
        description: 'Require multi-factor authentication',
      },
    ],
  },
  {
    id: 'generic_sso_saml',
    display_name: 'SSO / SAML',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 1000, latency_p50_ms: 100, latency_p99_ms: 500 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_concurrent_sso_sessions: 100000, max_apps: 1000 },
    az_config: { min_az: 2, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'IdP Unavailable',
        trigger_condition: 'identity provider down',
        impact: 'all SSO-dependent logins fail; no fallback',
        recovery_time_ms: 60000,
      },
      {
        name: 'Certificate Expiry',
        trigger_condition: 'SAML signing cert expires without rotation',
        impact: 'all SAML assertions rejected',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'security',
    properties: [
      {
        key: 'provider',
        label: 'Provider',
        type: 'select',
        default: 'okta',
        options: ['okta', 'auth0', 'azure_ad', 'google_workspace', 'pingidentity'],
        description: 'SSO provider',
      },
      {
        key: 'protocol',
        label: 'Protocol',
        type: 'select',
        default: 'saml',
        options: ['saml', 'oidc', 'ldap'],
        description: 'Federation protocol',
      },
      {
        key: 'session_ttl_h',
        label: 'Session TTL',
        type: 'number',
        default: 8,
        min: 1,
        max: 168,
        unit: 'h',
        description: 'SSO session duration',
      },
    ],
  },
  {
    id: 'generic_api_key_manager',
    display_name: 'API Key Manager',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 2, latency_p99_ms: 15 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'In-memory cache validation; mostly flat curve',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_api_keys: 1000000, max_key_length_bytes: 64 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Key Cache Miss',
        trigger_condition: 'cache eviction or restart loses key cache',
        impact: 'validation requires DB lookup; latency spike',
        recovery_time_ms: 5000,
      },
      {
        name: 'Key Leak',
        trigger_condition: 'key exposed in logs or client code',
        impact: 'unauthorized access until key revoked',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'security',
    properties: [
      {
        key: 'hashing_algorithm',
        label: 'Key Hashing',
        type: 'select',
        default: 'sha256',
        options: ['sha256', 'sha512', 'bcrypt'],
        description: 'Algorithm for storing API keys',
      },
      {
        key: 'prefix_visible',
        label: 'Visible Prefix Length',
        type: 'number',
        default: 8,
        min: 4,
        max: 16,
        description: 'Key prefix shown in UI for identification',
      },
      {
        key: 'rate_limit_per_key',
        label: 'Rate Limit Per Key',
        type: 'number',
        default: 1000,
        min: 1,
        max: 1000000,
        unit: 'req/s',
        description: 'Per-key rate limit',
      },
    ],
  },
  {
    id: 'generic_secrets_manager',
    display_name: 'Secrets Manager',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 10, latency_p99_ms: 80 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_secrets: 500000, max_secret_size_kb: 64 },
    az_config: null,
    failure_modes: [
      {
        name: 'API Throttle',
        trigger_condition: 'GetSecretValue calls > quota (10,000/s typical)',
        impact: 'application fails to fetch credentials',
        recovery_time_ms: 0,
      },
      {
        name: 'Rotation Failure',
        trigger_condition: 'Lambda rotation function fails',
        impact: 'secret not rotated; manual intervention required',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'secret/month', base_cost_usd: 0.4, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'security',
    properties: [
      {
        key: 'rotation_days',
        label: 'Auto-Rotation',
        type: 'number',
        default: 30,
        min: 0,
        max: 365,
        unit: 'days',
        description: 'Rotation interval (0 = disabled)',
      },
      {
        key: 'encryption_key',
        label: 'Encryption',
        type: 'select',
        default: 'managed',
        options: ['managed', 'customer_kms'],
        description: 'Encryption key type',
      },
      {
        key: 'cross_region_replication',
        label: 'Cross-Region Replication',
        type: 'boolean',
        default: false,
        description: 'Replicate secrets to other regions',
      },
    ],
  },
  {
    id: 'generic_certificate_authority',
    display_name: 'Certificate Authority',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 100, latency_p50_ms: 200, latency_p99_ms: 1000 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_certs_issued_per_month: 10000, max_cert_lifetime_days: 825 },
    az_config: null,
    failure_modes: [
      {
        name: 'Root CA Compromise',
        trigger_condition: 'root CA private key leaked',
        impact: 'all issued certs must be revoked; mass certificate rotation',
        recovery_time_ms: 0,
      },
      {
        name: 'OCSP Responder Down',
        trigger_condition: 'OCSP/CRL service unavailable',
        impact: 'certificate validation fails; depends on soft/hard fail policy',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: { unit: 'cert/month', base_cost_usd: 0.75, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'security',
    properties: [
      {
        key: 'key_algorithm',
        label: 'Key Algorithm',
        type: 'select',
        default: 'RSA-2048',
        options: ['RSA-2048', 'RSA-4096', 'ECDSA-P256', 'ECDSA-P384'],
        description: 'Certificate key algorithm',
      },
      {
        key: 'cert_lifetime_days',
        label: 'Cert Lifetime',
        type: 'number',
        default: 365,
        min: 1,
        max: 825,
        unit: 'days',
        description: 'Default certificate validity period',
      },
      {
        key: 'auto_renewal',
        label: 'Auto Renewal',
        type: 'boolean',
        default: true,
        description: 'Automatically renew expiring certificates',
      },
    ],
  },
  {
    id: 'generic_rate_limiter',
    display_name: 'Rate Limiter',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 100000, latency_p50_ms: 0.5, latency_p99_ms: 5 },
    saturation_curve: {
      coefficients: [1, 0.05, 0.5],
      description: 'Redis-backed; very fast; overhead minimal',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_windows: 1000000, max_window_size_s: 3600 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Redis Backend Failure',
        trigger_condition: 'Redis unreachable',
        impact: 'rate limiter fails open or closed depending on config',
        recovery_time_ms: 5000,
      },
      {
        name: 'Clock Drift',
        trigger_condition: 'NTP desync between nodes',
        impact: 'sliding window calculation incorrect; over/under limiting',
        recovery_time_ms: 0,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'security',
    properties: [
      {
        key: 'algorithm',
        label: 'Algorithm',
        type: 'select',
        default: 'sliding_window',
        options: ['fixed_window', 'sliding_window', 'token_bucket', 'leaky_bucket'],
        description: 'Rate limiting algorithm',
      },
      {
        key: 'limit',
        label: 'Request Limit',
        type: 'number',
        default: 1000,
        min: 1,
        max: 1000000,
        description: 'Max requests per window',
      },
      {
        key: 'window_s',
        label: 'Window Size',
        type: 'number',
        default: 60,
        min: 1,
        max: 3600,
        unit: 's',
        description: 'Rate limit window size',
      },
    ],
  },
  {
    id: 'generic_ddos_protection',
    display_name: 'DDoS Protection',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 100000000, latency_p50_ms: 0.1, latency_p99_ms: 2 },
    saturation_curve: {
      coefficients: [1, 0.01, 0.05],
      description: 'Scrubbing capacity effectively unlimited in large deployments',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_mitigation_gbps: 10000, detection_latency_ms: 1000 },
    az_config: null,
    failure_modes: [
      {
        name: 'False Positive Mitigation',
        trigger_condition: 'legitimate traffic fingerprinted as attack',
        impact: 'legitimate users blocked during mitigation window',
        recovery_time_ms: 60000,
      },
      {
        name: 'Novel Attack Vector',
        trigger_condition: 'attack pattern not in known signatures',
        impact: 'mitigation delayed until pattern detected',
        recovery_time_ms: 300000,
      },
    ],
    cost_model: { unit: 'month', base_cost_usd: 3000, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'firewall',
    properties: [
      {
        key: 'protection_tier',
        label: 'Protection Tier',
        type: 'select',
        default: 'standard',
        options: ['standard', 'advanced'],
        description: 'DDoS protection level',
      },
      {
        key: 'always_on',
        label: 'Always-On Detection',
        type: 'boolean',
        default: true,
        description: 'Continuous traffic baselining',
      },
      {
        key: 'health_check_protection',
        label: 'Health Check Protection',
        type: 'boolean',
        default: true,
        description: 'Protect health check endpoints',
      },
    ],
  },
  {
    id: 'generic_zero_trust_gateway',
    display_name: 'Zero Trust Gateway',
    category: ComponentCategory.Security,
    generic_equivalent: null,
    capacity: { max_rps: 50000, latency_p50_ms: 3, latency_p99_ms: 20 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_users: 100000, max_apps: 500 },
    az_config: null,
    failure_modes: [
      {
        name: 'Identity Provider Outage',
        trigger_condition: 'IdP unreachable',
        impact: 'all new connections blocked; existing sessions may persist',
        recovery_time_ms: 30000,
      },
      {
        name: 'Policy Misconfiguration',
        trigger_condition: 'overly permissive or restrictive policy deployed',
        impact: 'unintended access or denial of service',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'user/month', base_cost_usd: 5, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'security',
    properties: [
      {
        key: 'device_trust',
        label: 'Device Trust',
        type: 'boolean',
        default: true,
        description: 'Require device attestation',
      },
      {
        key: 'continuous_auth',
        label: 'Continuous Auth',
        type: 'boolean',
        default: true,
        description: 'Re-validate auth on each request',
      },
      {
        key: 'micro_segmentation',
        label: 'Micro-Segmentation',
        type: 'boolean',
        default: true,
        description: 'Enforce least-privilege network segments',
      },
    ],
  },
];
