import type { CBREntry } from '@vexo/types';
import { ComponentCategory } from '@vexo/types';

const QUAD_CURVE = {
  coefficients: [1, 0.2, 1.8],
  description: 'Latency roughly doubles at 80% load, 3x at 95%',
};

export const storageComponents: CBREntry[] = [
  {
    id: 'generic_object_storage',
    display_name: 'Object Storage',
    category: ComponentCategory.Storage,
    generic_equivalent: null,
    capacity: { max_rps: 5500, latency_p50_ms: 20, latency_p99_ms: 200 },
    saturation_curve: {
      coefficients: [1, 0.1, 0.8],
      description: 'Scales horizontally; PUT/GET rates vary by key prefix',
    },
    cold_start: null,
    throttle_behaviour: 'reject_429',
    limits: { max_object_size_gb: 5000, max_put_rps_per_prefix: 3500, max_get_rps_per_prefix: 5500 },
    az_config: null,
    failure_modes: [
      {
        name: 'Prefix Hotspot',
        trigger_condition: 'sequential prefix keys exceed per-prefix rps limit',
        impact: 'slowdowns and 503 errors on hot prefix',
        recovery_time_ms: 0,
      },
      {
        name: 'Eventual Consistency Window',
        trigger_condition: 'read-after-write in different AZ',
        impact: 'stale read up to a few seconds',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: { unit: 'GB/month', base_cost_usd: 0.023, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 's3',
    properties: [
      {
        key: 'storage_class',
        label: 'Storage Class',
        type: 'select',
        default: 'standard',
        options: ['standard', 'infrequent-access', 'glacier', 'deep-archive'],
        description: 'Storage tier / access frequency',
      },
      {
        key: 'versioning',
        label: 'Versioning',
        type: 'boolean',
        default: false,
        description: 'Enable object versioning',
      },
      {
        key: 'replication',
        label: 'Cross-Region Replication',
        type: 'boolean',
        default: false,
        description: 'Replicate objects to another region',
      },
      {
        key: 'encryption',
        label: 'Encryption',
        type: 'select',
        default: 'SSE-S3',
        options: ['none', 'SSE-S3', 'SSE-KMS', 'SSE-C'],
        description: 'Server-side encryption',
      },
    ],
  },
  {
    id: 'generic_block_storage',
    display_name: 'Block Storage',
    category: ComponentCategory.Storage,
    generic_equivalent: null,
    capacity: { max_rps: 64000, latency_p50_ms: 0.5, latency_p99_ms: 2 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_iops: 256000, max_throughput_mbs: 4000, max_volume_size_tb: 64 },
    az_config: { min_az: 1, max_az: 1, cross_az_latency_ms: 0 },
    failure_modes: [
      {
        name: 'IOPS Exhaustion',
        trigger_condition: 'io_ops >= max_iops',
        impact: 'I/O queue depth grows; application stalls',
        recovery_time_ms: 0,
      },
      {
        name: 'Volume Detachment',
        trigger_condition: 'host failure or AZ issue',
        impact: 'volume must be reattached to replacement instance',
        recovery_time_ms: 30000,
      },
    ],
    cost_model: { unit: 'GB/month', base_cost_usd: 0.08, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'ebs',
    properties: [
      {
        key: 'volume_type',
        label: 'Volume Type',
        type: 'select',
        default: 'gp3',
        options: ['gp2', 'gp3', 'io1', 'io2', 'st1', 'sc1'],
        description: 'EBS volume type',
      },
      {
        key: 'size_gb',
        label: 'Size',
        type: 'number',
        default: 100,
        min: 1,
        max: 65536,
        unit: 'GB',
        description: 'Volume size',
      },
      {
        key: 'iops',
        label: 'IOPS',
        type: 'number',
        default: 3000,
        min: 100,
        max: 256000,
        description: 'Provisioned IOPS',
      },
      {
        key: 'encrypted',
        label: 'Encrypted',
        type: 'boolean',
        default: true,
        description: 'Enable volume encryption',
      },
    ],
  },
  {
    id: 'generic_file_storage_nfs',
    display_name: 'File Storage (NFS)',
    category: ComponentCategory.Storage,
    generic_equivalent: null,
    capacity: { max_rps: 10000, latency_p50_ms: 2, latency_p99_ms: 20 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_throughput_mbs: 10000, max_file_size_gb: 52000, max_storage_pb: 10 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 2 },
    failure_modes: [
      {
        name: 'Throughput Throttle',
        trigger_condition: 'throughput > provisioned burst limit',
        impact: 'I/O latency spikes; application stalls',
        recovery_time_ms: 0,
      },
      {
        name: 'Mount Target Failure',
        trigger_condition: 'AZ-specific mount target down',
        impact: 'instances in that AZ lose filesystem access',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: { unit: 'GB/month', base_cost_usd: 0.3, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'efs',
    properties: [
      {
        key: 'throughput_mode',
        label: 'Throughput Mode',
        type: 'select',
        default: 'bursting',
        options: ['bursting', 'provisioned', 'elastic'],
        description: 'File system throughput mode',
      },
      {
        key: 'performance_mode',
        label: 'Performance Mode',
        type: 'select',
        default: 'generalPurpose',
        options: ['generalPurpose', 'maxIO'],
        description: 'File system performance mode',
      },
      {
        key: 'lifecycle_policy',
        label: 'Lifecycle Policy',
        type: 'select',
        default: '30 days',
        options: ['none', '7 days', '14 days', '30 days', '60 days', '90 days'],
        description: 'Auto-transition to IA after inactivity',
      },
    ],
  },
  {
    id: 'generic_data_lake',
    display_name: 'Data Lake',
    category: ComponentCategory.Storage,
    generic_equivalent: 'generic_object_storage',
    capacity: { max_rps: 1000, latency_p50_ms: 100, latency_p99_ms: 2000 },
    saturation_curve: {
      coefficients: [1, 0.5, 2.0],
      description: 'Batch scan throughput-bound; concurrent scans compete for bandwidth',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_catalog_size_gb: 1000, max_object_size_tb: 5 },
    az_config: null,
    failure_modes: [
      {
        name: 'Small File Problem',
        trigger_condition: 'millions of tiny files in single prefix',
        impact: 'LIST operations slow; metadata scanning expensive',
        recovery_time_ms: 0,
      },
      {
        name: 'Schema Evolution Mismatch',
        trigger_condition: 'new schema incompatible with old partitions',
        impact: 'query failures on historical data',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'GB/month', base_cost_usd: 0.023, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 's3',
    properties: [
      {
        key: 'format',
        label: 'Storage Format',
        type: 'select',
        default: 'parquet',
        options: ['parquet', 'orc', 'avro', 'json', 'csv'],
        description: 'Data file format',
      },
      {
        key: 'partitioning',
        label: 'Partition Strategy',
        type: 'select',
        default: 'date',
        options: ['none', 'date', 'hour', 'custom'],
        description: 'Data partitioning scheme',
      },
      {
        key: 'catalog',
        label: 'Data Catalog',
        type: 'boolean',
        default: true,
        description: 'Enable metadata catalog (Glue/Hive)',
      },
    ],
  },
  {
    id: 'generic_cold_archive',
    display_name: 'Cold Archive',
    category: ComponentCategory.Storage,
    generic_equivalent: 'generic_object_storage',
    capacity: { max_rps: 10, latency_p50_ms: 30000, latency_p99_ms: 240000 },
    saturation_curve: {
      coefficients: [1, 0.05, 0.2],
      description: 'Retrieval time dominates; throughput largely flat',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { min_storage_duration_days: 90, max_retrieval_rate_gb_per_hour: 150 },
    az_config: null,
    failure_modes: [
      {
        name: 'Retrieval Throttle',
        trigger_condition: 'restore requests > provisioned retrieval capacity',
        impact: 'restore jobs queue; hours of delay',
        recovery_time_ms: 0,
      },
      {
        name: 'Early Deletion Fee',
        trigger_condition: 'delete object before min_storage_duration_days',
        impact: 'charged for remaining storage duration',
        recovery_time_ms: 0,
      },
    ],
    cost_model: { unit: 'GB/month', base_cost_usd: 0.00099, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'glacier',
    properties: [
      {
        key: 'retrieval_tier',
        label: 'Retrieval Tier',
        type: 'select',
        default: 'standard',
        options: ['expedited', 'standard', 'bulk'],
        description: 'Retrieval speed (expedited=1–5min, standard=3–5h, bulk=5–12h)',
      },
      {
        key: 'min_duration_days',
        label: 'Min Storage Duration',
        type: 'number',
        default: 90,
        min: 90,
        max: 180,
        unit: 'days',
        description: 'Minimum storage commitment',
      },
      {
        key: 'vault_lock',
        label: 'Vault Lock',
        type: 'boolean',
        default: false,
        description: 'Enable compliance vault lock policy',
      },
    ],
  },
  {
    id: 'generic_hdfs',
    display_name: 'HDFS',
    category: ComponentCategory.Storage,
    generic_equivalent: null,
    capacity: { max_rps: 5000, latency_p50_ms: 10, latency_p99_ms: 100 },
    saturation_curve: {
      coefficients: [1, 0.3, 2.5],
      description: 'NameNode is single bottleneck; DataNode throughput scales linearly',
    },
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_namenode_objects: 300000000, default_block_size_mb: 128 },
    az_config: { min_az: 1, max_az: 1, cross_az_latency_ms: 0 },
    failure_modes: [
      {
        name: 'NameNode SPOF',
        trigger_condition: 'NameNode process failure (non-HA setup)',
        impact: 'complete cluster unavailability',
        recovery_time_ms: 300000,
      },
      {
        name: 'DataNode Failure',
        trigger_condition: 'DataNode disk or process failure',
        impact: 'block replication triggered; temporary read degradation',
        recovery_time_ms: 60000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'hadoop',
    properties: [
      {
        key: 'datanode_count',
        label: 'DataNode Count',
        type: 'number',
        default: 3,
        min: 3,
        max: 1000,
        description: 'Number of HDFS DataNodes',
      },
      {
        key: 'replication_factor',
        label: 'Replication Factor',
        type: 'number',
        default: 3,
        min: 1,
        max: 5,
        description: 'Block replication factor',
      },
      {
        key: 'block_size_mb',
        label: 'Block Size',
        type: 'number',
        default: 128,
        min: 64,
        max: 1024,
        unit: 'MB',
        description: 'HDFS block size',
      },
    ],
  },
  {
    id: 'generic_content_repository',
    display_name: 'Content Repository',
    category: ComponentCategory.Storage,
    generic_equivalent: 'generic_object_storage',
    capacity: { max_rps: 2000, latency_p50_ms: 30, latency_p99_ms: 300 },
    saturation_curve: QUAD_CURVE,
    cold_start: null,
    throttle_behaviour: 'queue',
    limits: { max_asset_size_gb: 50, max_storage_pb: 1 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 5 },
    failure_modes: [
      {
        name: 'CDN Origin Overload',
        trigger_condition: 'CDN cache miss storm hits origin',
        impact: 'origin bandwidth saturated, 503s',
        recovery_time_ms: 60000,
      },
      {
        name: 'Metadata DB Contention',
        trigger_condition: 'concurrent asset uploads > DB write capacity',
        impact: 'upload failures or delays',
        recovery_time_ms: 5000,
      },
    ],
    cost_model: { unit: 'GB/month', base_cost_usd: 0.05, scale_factor: 1 },
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'custom',
    iconId: 'app_server',
    properties: [
      {
        key: 'max_asset_size_mb',
        label: 'Max Asset Size',
        type: 'number',
        default: 512,
        min: 1,
        max: 51200,
        unit: 'MB',
        description: 'Maximum uploadable asset size',
      },
      {
        key: 'cdn_enabled',
        label: 'CDN Distribution',
        type: 'boolean',
        default: true,
        description: 'Serve assets via CDN',
      },
      {
        key: 'virus_scan',
        label: 'Virus Scanning',
        type: 'boolean',
        default: false,
        description: 'Scan uploads for malware',
      },
    ],
  },
  {
    id: 'generic_distributed_cache',
    display_name: 'Distributed Cache',
    category: ComponentCategory.Storage,
    generic_equivalent: 'generic_redis',
    capacity: { max_rps: 500000, latency_p50_ms: 0.3, latency_p99_ms: 3 },
    saturation_curve: {
      coefficients: [1, 0.05, 0.5],
      description: 'Memory-bound; near-linear scale with node count',
    },
    cold_start: null,
    throttle_behaviour: 'shed',
    limits: { max_item_size_mb: 1, max_connections_per_node: 65000 },
    az_config: { min_az: 1, max_az: 3, cross_az_latency_ms: 1 },
    failure_modes: [
      {
        name: 'Thundering Herd',
        trigger_condition: 'cache cold start after flush/restart',
        impact: 'all requests miss cache, DB hammered',
        recovery_time_ms: 60000,
      },
      {
        name: 'Node Failure Resharding',
        trigger_condition: 'cache node failure',
        impact: 'keys rehashed; cache miss burst during rehash',
        recovery_time_ms: 10000,
      },
    ],
    cost_model: null,
    source_citations: [],
    last_validated: '2026-01-01',
    iconType: 'brand',
    iconId: 'memcached',
    properties: [
      {
        key: 'node_count',
        label: 'Node Count',
        type: 'number',
        default: 3,
        min: 1,
        max: 100,
        description: 'Number of cache nodes',
      },
      {
        key: 'memory_gb_per_node',
        label: 'Memory Per Node',
        type: 'number',
        default: 8,
        min: 1,
        max: 512,
        unit: 'GB',
        description: 'Memory per cache node',
      },
      {
        key: 'protocol',
        label: 'Protocol',
        type: 'select',
        default: 'memcached',
        options: ['memcached', 'redis'],
        description: 'Cache protocol',
      },
    ],
  },
];
